// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbft.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PbftMsgType int32

const (
	PbftMsgType_PBFT_MSG_UNDEFINED  PbftMsgType = 0
	PbftMsgType_PBFT_MSG_REQUEST    PbftMsgType = 1
	PbftMsgType_PBFT_MSG_PREPREPARE PbftMsgType = 2
	PbftMsgType_PBFT_MSG_PREPARE    PbftMsgType = 3
	PbftMsgType_PBFT_MSG_COMMIT     PbftMsgType = 4
	PbftMsgType_PBFT_MSG_CHECKPOINT PbftMsgType = 5
)

var PbftMsgType_name = map[int32]string{
	0: "PBFT_MSG_UNDEFINED",
	1: "PBFT_MSG_REQUEST",
	2: "PBFT_MSG_PREPREPARE",
	3: "PBFT_MSG_PREPARE",
	4: "PBFT_MSG_COMMIT",
	5: "PBFT_MSG_CHECKPOINT",
}

var PbftMsgType_value = map[string]int32{
	"PBFT_MSG_UNDEFINED":  0,
	"PBFT_MSG_REQUEST":    1,
	"PBFT_MSG_PREPREPARE": 2,
	"PBFT_MSG_PREPARE":    3,
	"PBFT_MSG_COMMIT":     4,
	"PBFT_MSG_CHECKPOINT": 5,
}

func (x PbftMsgType) String() string {
	return proto.EnumName(PbftMsgType_name, int32(x))
}

func (PbftMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6cc19f28ccff0670, []int{0}
}

type PbftMsg struct {
	Type PbftMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PbftMsgType" json:"type,omitempty"`
	// used for preprepare, prepare, commit
	View uint64 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	// used for preprepare, prepare, commit, checkpoint
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// used for preprepare, prepare, commit, request
	// TODO: Most messages should contain only the hash of the request - KEP-344
	Request *PbftRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	// Needed for prepare, commit, request, checkpoing, but included always for clarity. This is the sender's uuid.
	Sender string `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	// for checkpoints
	StateHash            string   `protobuf:"bytes,6,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbftMsg) Reset()         { *m = PbftMsg{} }
func (m *PbftMsg) String() string { return proto.CompactTextString(m) }
func (*PbftMsg) ProtoMessage()    {}
func (*PbftMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc19f28ccff0670, []int{0}
}

func (m *PbftMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbftMsg.Unmarshal(m, b)
}
func (m *PbftMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbftMsg.Marshal(b, m, deterministic)
}
func (m *PbftMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbftMsg.Merge(m, src)
}
func (m *PbftMsg) XXX_Size() int {
	return xxx_messageInfo_PbftMsg.Size(m)
}
func (m *PbftMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PbftMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PbftMsg proto.InternalMessageInfo

func (m *PbftMsg) GetType() PbftMsgType {
	if m != nil {
		return m.Type
	}
	return PbftMsgType_PBFT_MSG_UNDEFINED
}

func (m *PbftMsg) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PbftMsg) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PbftMsg) GetRequest() *PbftRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PbftMsg) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PbftMsg) GetStateHash() string {
	if m != nil {
		return m.StateHash
	}
	return ""
}

type PbftRequest struct {
	Operation            *DatabaseMsg `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Timestamp            uint64       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Client               string       `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PbftRequest) Reset()         { *m = PbftRequest{} }
func (m *PbftRequest) String() string { return proto.CompactTextString(m) }
func (*PbftRequest) ProtoMessage()    {}
func (*PbftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc19f28ccff0670, []int{1}
}

func (m *PbftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbftRequest.Unmarshal(m, b)
}
func (m *PbftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbftRequest.Marshal(b, m, deterministic)
}
func (m *PbftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbftRequest.Merge(m, src)
}
func (m *PbftRequest) XXX_Size() int {
	return xxx_messageInfo_PbftRequest.Size(m)
}
func (m *PbftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PbftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PbftRequest proto.InternalMessageInfo

func (m *PbftRequest) GetOperation() *DatabaseMsg {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *PbftRequest) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PbftRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.PbftMsgType", PbftMsgType_name, PbftMsgType_value)
	proto.RegisterType((*PbftMsg)(nil), "pb.pbft_msg")
	proto.RegisterType((*PbftRequest)(nil), "pb.pbft_request")
}

func init() { proto.RegisterFile("pbft.proto", fileDescriptor_6cc19f28ccff0670) }

var fileDescriptor_6cc19f28ccff0670 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x5f, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xbf, 0x81, 0xc2, 0x47, 0xaf, 0x8a, 0xf5, 0x62, 0xb0, 0x21, 0x9a, 0x34, 0x24, 0x26,
	0x0d, 0x0f, 0x7d, 0xc0, 0x15, 0x28, 0x14, 0x21, 0x86, 0x3f, 0x0e, 0xe5, 0xb9, 0x99, 0xc2, 0x28,
	0x4d, 0xa4, 0xad, 0x9d, 0x51, 0xe3, 0x56, 0x5c, 0x8f, 0x0b, 0x33, 0x1d, 0xdb, 0x22, 0x49, 0x1f,
	0xee, 0xfd, 0x9d, 0x93, 0xd3, 0x39, 0x33, 0x00, 0x49, 0xf0, 0x24, 0x9d, 0x24, 0x8d, 0x65, 0x8c,
	0x95, 0x24, 0xe8, 0x34, 0x37, 0x4c, 0xb2, 0x80, 0x09, 0xfe, 0xcb, 0xba, 0xdf, 0x04, 0x1a, 0x99,
	0xc5, 0xdf, 0x89, 0x67, 0xbc, 0x06, 0x4d, 0x7e, 0x26, 0xdc, 0x24, 0x16, 0xb1, 0x9b, 0xfd, 0x33,
	0x27, 0x09, 0x9c, 0x42, 0xf3, 0x33, 0x81, 0x2a, 0x19, 0x11, 0xb4, 0xf7, 0x90, 0x7f, 0x98, 0x15,
	0x8b, 0xd8, 0x1a, 0x55, 0x33, 0x76, 0xa0, 0x21, 0xf8, 0xeb, 0x1b, 0x8f, 0xd6, 0xdc, 0xac, 0x2a,
	0x5e, 0xee, 0xd8, 0x83, 0xff, 0x69, 0x36, 0x0b, 0x69, 0x6a, 0x16, 0xb1, 0x8f, 0xfa, 0x46, 0x99,
	0x9c, 0x73, 0x5a, 0x18, 0xb0, 0x0d, 0x75, 0xc1, 0xa3, 0x0d, 0x4f, 0xcd, 0x9a, 0x45, 0x6c, 0x9d,
	0xe6, 0x1b, 0x5e, 0x01, 0x08, 0xc9, 0x24, 0xf7, 0xb7, 0x4c, 0x6c, 0xcd, 0xba, 0xd2, 0x74, 0x45,
	0xc6, 0x4c, 0x6c, 0xbb, 0x12, 0x8e, 0xff, 0xe6, 0xa1, 0x03, 0x7a, 0x9c, 0xf0, 0x94, 0xc9, 0x30,
	0x8e, 0x54, 0x9d, 0xfc, 0xa7, 0x45, 0xfb, 0xac, 0x12, 0xdd, 0x5b, 0xf0, 0x12, 0x74, 0x19, 0xee,
	0xb8, 0x90, 0x6c, 0x97, 0xe4, 0xbd, 0xf6, 0x20, 0x3b, 0xd4, 0xfa, 0x25, 0xe4, 0x91, 0x54, 0xd5,
	0x74, 0x9a, 0x6f, 0xbd, 0x2f, 0x02, 0x27, 0x07, 0x17, 0x84, 0x6d, 0xc0, 0xc5, 0xdd, 0xc8, 0xf3,
	0xa7, 0xcb, 0x7b, 0x7f, 0x35, 0x1b, 0xba, 0xa3, 0xc9, 0xcc, 0x1d, 0x1a, 0xff, 0xf0, 0x1c, 0x8c,
	0x92, 0x53, 0xf7, 0x71, 0xe5, 0x2e, 0x3d, 0x83, 0xe0, 0x05, 0xb4, 0x4a, 0xba, 0xa0, 0x6e, 0xf6,
	0xdd, 0x52, 0xd7, 0xa8, 0x1c, 0xd8, 0x0b, 0x5a, 0xc5, 0x16, 0x9c, 0x96, 0x74, 0x30, 0x9f, 0x4e,
	0x27, 0x9e, 0xa1, 0x1d, 0x64, 0x0c, 0xc6, 0xee, 0xe0, 0x61, 0x31, 0x9f, 0xcc, 0x3c, 0xa3, 0x16,
	0xd4, 0xd5, 0x03, 0xdf, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x86, 0x3f, 0x12, 0x99, 0x02, 0x02,
	0x00, 0x00,
}
