// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DatabaseMsg struct {
	Header *DatabaseHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*DatabaseMsg_Create
	//	*DatabaseMsg_Read
	//	*DatabaseMsg_Update
	//	*DatabaseMsg_Delete
	//	*DatabaseMsg_Has
	//	*DatabaseMsg_Keys
	//	*DatabaseMsg_Size
	Msg                  isDatabaseMsg_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DatabaseMsg) Reset()         { *m = DatabaseMsg{} }
func (m *DatabaseMsg) String() string { return proto.CompactTextString(m) }
func (*DatabaseMsg) ProtoMessage()    {}
func (*DatabaseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{0}
}
func (m *DatabaseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseMsg.Unmarshal(m, b)
}
func (m *DatabaseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseMsg.Marshal(b, m, deterministic)
}
func (dst *DatabaseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseMsg.Merge(dst, src)
}
func (m *DatabaseMsg) XXX_Size() int {
	return xxx_messageInfo_DatabaseMsg.Size(m)
}
func (m *DatabaseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseMsg proto.InternalMessageInfo

type isDatabaseMsg_Msg interface {
	isDatabaseMsg_Msg()
}

type DatabaseMsg_Create struct {
	Create *DatabaseCreate `protobuf:"bytes,10,opt,name=create,proto3,oneof"`
}
type DatabaseMsg_Read struct {
	Read *DatabaseRead `protobuf:"bytes,11,opt,name=read,proto3,oneof"`
}
type DatabaseMsg_Update struct {
	Update *DatabaseUpdate `protobuf:"bytes,12,opt,name=update,proto3,oneof"`
}
type DatabaseMsg_Delete struct {
	Delete *DatabaseDelete `protobuf:"bytes,13,opt,name=delete,proto3,oneof"`
}
type DatabaseMsg_Has struct {
	Has *DatabaseHas `protobuf:"bytes,14,opt,name=has,proto3,oneof"`
}
type DatabaseMsg_Keys struct {
	Keys *DatabaseEmpty `protobuf:"bytes,15,opt,name=keys,proto3,oneof"`
}
type DatabaseMsg_Size struct {
	Size *DatabaseEmpty `protobuf:"bytes,16,opt,name=size,proto3,oneof"`
}

func (*DatabaseMsg_Create) isDatabaseMsg_Msg() {}
func (*DatabaseMsg_Read) isDatabaseMsg_Msg()   {}
func (*DatabaseMsg_Update) isDatabaseMsg_Msg() {}
func (*DatabaseMsg_Delete) isDatabaseMsg_Msg() {}
func (*DatabaseMsg_Has) isDatabaseMsg_Msg()    {}
func (*DatabaseMsg_Keys) isDatabaseMsg_Msg()   {}
func (*DatabaseMsg_Size) isDatabaseMsg_Msg()   {}

func (m *DatabaseMsg) GetMsg() isDatabaseMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *DatabaseMsg) GetHeader() *DatabaseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DatabaseMsg) GetCreate() *DatabaseCreate {
	if x, ok := m.GetMsg().(*DatabaseMsg_Create); ok {
		return x.Create
	}
	return nil
}

func (m *DatabaseMsg) GetRead() *DatabaseRead {
	if x, ok := m.GetMsg().(*DatabaseMsg_Read); ok {
		return x.Read
	}
	return nil
}

func (m *DatabaseMsg) GetUpdate() *DatabaseUpdate {
	if x, ok := m.GetMsg().(*DatabaseMsg_Update); ok {
		return x.Update
	}
	return nil
}

func (m *DatabaseMsg) GetDelete() *DatabaseDelete {
	if x, ok := m.GetMsg().(*DatabaseMsg_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *DatabaseMsg) GetHas() *DatabaseHas {
	if x, ok := m.GetMsg().(*DatabaseMsg_Has); ok {
		return x.Has
	}
	return nil
}

func (m *DatabaseMsg) GetKeys() *DatabaseEmpty {
	if x, ok := m.GetMsg().(*DatabaseMsg_Keys); ok {
		return x.Keys
	}
	return nil
}

func (m *DatabaseMsg) GetSize() *DatabaseEmpty {
	if x, ok := m.GetMsg().(*DatabaseMsg_Size); ok {
		return x.Size
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DatabaseMsg) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DatabaseMsg_OneofMarshaler, _DatabaseMsg_OneofUnmarshaler, _DatabaseMsg_OneofSizer, []interface{}{
		(*DatabaseMsg_Create)(nil),
		(*DatabaseMsg_Read)(nil),
		(*DatabaseMsg_Update)(nil),
		(*DatabaseMsg_Delete)(nil),
		(*DatabaseMsg_Has)(nil),
		(*DatabaseMsg_Keys)(nil),
		(*DatabaseMsg_Size)(nil),
	}
}

func _DatabaseMsg_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DatabaseMsg)
	// msg
	switch x := m.Msg.(type) {
	case *DatabaseMsg_Create:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Create); err != nil {
			return err
		}
	case *DatabaseMsg_Read:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Read); err != nil {
			return err
		}
	case *DatabaseMsg_Update:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Update); err != nil {
			return err
		}
	case *DatabaseMsg_Delete:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Delete); err != nil {
			return err
		}
	case *DatabaseMsg_Has:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Has); err != nil {
			return err
		}
	case *DatabaseMsg_Keys:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Keys); err != nil {
			return err
		}
	case *DatabaseMsg_Size:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Size); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DatabaseMsg.Msg has unexpected type %T", x)
	}
	return nil
}

func _DatabaseMsg_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DatabaseMsg)
	switch tag {
	case 10: // msg.create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseCreate)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Create{msg}
		return true, err
	case 11: // msg.read
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseRead)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Read{msg}
		return true, err
	case 12: // msg.update
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseUpdate)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Update{msg}
		return true, err
	case 13: // msg.delete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseDelete)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Delete{msg}
		return true, err
	case 14: // msg.has
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseHas)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Has{msg}
		return true, err
	case 15: // msg.keys
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseEmpty)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Keys{msg}
		return true, err
	case 16: // msg.size
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseEmpty)
		err := b.DecodeMessage(msg)
		m.Msg = &DatabaseMsg_Size{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DatabaseMsg_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DatabaseMsg)
	// msg
	switch x := m.Msg.(type) {
	case *DatabaseMsg_Create:
		s := proto.Size(x.Create)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseMsg_Read:
		s := proto.Size(x.Read)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseMsg_Update:
		s := proto.Size(x.Update)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseMsg_Delete:
		s := proto.Size(x.Delete)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseMsg_Has:
		s := proto.Size(x.Has)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseMsg_Keys:
		s := proto.Size(x.Keys)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseMsg_Size:
		s := proto.Size(x.Size)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DatabaseRedirectResponse struct {
	LeaderId             string   `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderName           string   `protobuf:"bytes,2,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderHost           string   `protobuf:"bytes,3,opt,name=leader_host,json=leaderHost,proto3" json:"leader_host,omitempty"`
	LeaderPort           uint32   `protobuf:"varint,4,opt,name=leader_port,json=leaderPort,proto3" json:"leader_port,omitempty"`
	LeaderHttpPort       uint32   `protobuf:"varint,5,opt,name=leader_http_port,json=leaderHttpPort,proto3" json:"leader_http_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseRedirectResponse) Reset()         { *m = DatabaseRedirectResponse{} }
func (m *DatabaseRedirectResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseRedirectResponse) ProtoMessage()    {}
func (*DatabaseRedirectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{1}
}
func (m *DatabaseRedirectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseRedirectResponse.Unmarshal(m, b)
}
func (m *DatabaseRedirectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseRedirectResponse.Marshal(b, m, deterministic)
}
func (dst *DatabaseRedirectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseRedirectResponse.Merge(dst, src)
}
func (m *DatabaseRedirectResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseRedirectResponse.Size(m)
}
func (m *DatabaseRedirectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseRedirectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseRedirectResponse proto.InternalMessageInfo

func (m *DatabaseRedirectResponse) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *DatabaseRedirectResponse) GetLeaderName() string {
	if m != nil {
		return m.LeaderName
	}
	return ""
}

func (m *DatabaseRedirectResponse) GetLeaderHost() string {
	if m != nil {
		return m.LeaderHost
	}
	return ""
}

func (m *DatabaseRedirectResponse) GetLeaderPort() uint32 {
	if m != nil {
		return m.LeaderPort
	}
	return 0
}

func (m *DatabaseRedirectResponse) GetLeaderHttpPort() uint32 {
	if m != nil {
		return m.LeaderHttpPort
	}
	return 0
}

type DatabaseHeader struct {
	DbUuid               string   `protobuf:"bytes,1,opt,name=db_uuid,json=dbUuid,proto3" json:"db_uuid,omitempty"`
	TransactionId        uint64   `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHeader) Reset()         { *m = DatabaseHeader{} }
func (m *DatabaseHeader) String() string { return proto.CompactTextString(m) }
func (*DatabaseHeader) ProtoMessage()    {}
func (*DatabaseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{2}
}
func (m *DatabaseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHeader.Unmarshal(m, b)
}
func (m *DatabaseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHeader.Marshal(b, m, deterministic)
}
func (dst *DatabaseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHeader.Merge(dst, src)
}
func (m *DatabaseHeader) XXX_Size() int {
	return xxx_messageInfo_DatabaseHeader.Size(m)
}
func (m *DatabaseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHeader proto.InternalMessageInfo

func (m *DatabaseHeader) GetDbUuid() string {
	if m != nil {
		return m.DbUuid
	}
	return ""
}

func (m *DatabaseHeader) GetTransactionId() uint64 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

type DatabaseCreate struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseCreate) Reset()         { *m = DatabaseCreate{} }
func (m *DatabaseCreate) String() string { return proto.CompactTextString(m) }
func (*DatabaseCreate) ProtoMessage()    {}
func (*DatabaseCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{3}
}
func (m *DatabaseCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseCreate.Unmarshal(m, b)
}
func (m *DatabaseCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseCreate.Marshal(b, m, deterministic)
}
func (dst *DatabaseCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseCreate.Merge(dst, src)
}
func (m *DatabaseCreate) XXX_Size() int {
	return xxx_messageInfo_DatabaseCreate.Size(m)
}
func (m *DatabaseCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseCreate.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseCreate proto.InternalMessageInfo

func (m *DatabaseCreate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseCreate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DatabaseRead struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseRead) Reset()         { *m = DatabaseRead{} }
func (m *DatabaseRead) String() string { return proto.CompactTextString(m) }
func (*DatabaseRead) ProtoMessage()    {}
func (*DatabaseRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{4}
}
func (m *DatabaseRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseRead.Unmarshal(m, b)
}
func (m *DatabaseRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseRead.Marshal(b, m, deterministic)
}
func (dst *DatabaseRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseRead.Merge(dst, src)
}
func (m *DatabaseRead) XXX_Size() int {
	return xxx_messageInfo_DatabaseRead.Size(m)
}
func (m *DatabaseRead) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseRead.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseRead proto.InternalMessageInfo

func (m *DatabaseRead) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseUpdate struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseUpdate) Reset()         { *m = DatabaseUpdate{} }
func (m *DatabaseUpdate) String() string { return proto.CompactTextString(m) }
func (*DatabaseUpdate) ProtoMessage()    {}
func (*DatabaseUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{5}
}
func (m *DatabaseUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseUpdate.Unmarshal(m, b)
}
func (m *DatabaseUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseUpdate.Marshal(b, m, deterministic)
}
func (dst *DatabaseUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseUpdate.Merge(dst, src)
}
func (m *DatabaseUpdate) XXX_Size() int {
	return xxx_messageInfo_DatabaseUpdate.Size(m)
}
func (m *DatabaseUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseUpdate proto.InternalMessageInfo

func (m *DatabaseUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseUpdate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DatabaseDelete struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseDelete) Reset()         { *m = DatabaseDelete{} }
func (m *DatabaseDelete) String() string { return proto.CompactTextString(m) }
func (*DatabaseDelete) ProtoMessage()    {}
func (*DatabaseDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{6}
}
func (m *DatabaseDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseDelete.Unmarshal(m, b)
}
func (m *DatabaseDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseDelete.Marshal(b, m, deterministic)
}
func (dst *DatabaseDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseDelete.Merge(dst, src)
}
func (m *DatabaseDelete) XXX_Size() int {
	return xxx_messageInfo_DatabaseDelete.Size(m)
}
func (m *DatabaseDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseDelete.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseDelete proto.InternalMessageInfo

func (m *DatabaseDelete) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseHas struct {
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHas) Reset()         { *m = DatabaseHas{} }
func (m *DatabaseHas) String() string { return proto.CompactTextString(m) }
func (*DatabaseHas) ProtoMessage()    {}
func (*DatabaseHas) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{7}
}
func (m *DatabaseHas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHas.Unmarshal(m, b)
}
func (m *DatabaseHas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHas.Marshal(b, m, deterministic)
}
func (dst *DatabaseHas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHas.Merge(dst, src)
}
func (m *DatabaseHas) XXX_Size() int {
	return xxx_messageInfo_DatabaseHas.Size(m)
}
func (m *DatabaseHas) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHas.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHas proto.InternalMessageInfo

func (m *DatabaseHas) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseEmpty) Reset()         { *m = DatabaseEmpty{} }
func (m *DatabaseEmpty) String() string { return proto.CompactTextString(m) }
func (*DatabaseEmpty) ProtoMessage()    {}
func (*DatabaseEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{8}
}
func (m *DatabaseEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseEmpty.Unmarshal(m, b)
}
func (m *DatabaseEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseEmpty.Marshal(b, m, deterministic)
}
func (dst *DatabaseEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseEmpty.Merge(dst, src)
}
func (m *DatabaseEmpty) XXX_Size() int {
	return xxx_messageInfo_DatabaseEmpty.Size(m)
}
func (m *DatabaseEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseEmpty proto.InternalMessageInfo

type DatabaseResponse struct {
	Header *DatabaseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Success:
	//	*DatabaseResponse_Redirect
	//	*DatabaseResponse_Resp
	Success              isDatabaseResponse_Success `protobuf_oneof:"success"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DatabaseResponse) Reset()         { *m = DatabaseResponse{} }
func (m *DatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseResponse) ProtoMessage()    {}
func (*DatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{9}
}
func (m *DatabaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseResponse.Unmarshal(m, b)
}
func (m *DatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseResponse.Marshal(b, m, deterministic)
}
func (dst *DatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseResponse.Merge(dst, src)
}
func (m *DatabaseResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseResponse.Size(m)
}
func (m *DatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseResponse proto.InternalMessageInfo

type isDatabaseResponse_Success interface {
	isDatabaseResponse_Success()
}

type DatabaseResponse_Redirect struct {
	Redirect *DatabaseRedirectResponse `protobuf:"bytes,2,opt,name=redirect,proto3,oneof"`
}
type DatabaseResponse_Resp struct {
	Resp *DatabaseResponseResponse `protobuf:"bytes,3,opt,name=resp,proto3,oneof"`
}

func (*DatabaseResponse_Redirect) isDatabaseResponse_Success() {}
func (*DatabaseResponse_Resp) isDatabaseResponse_Success()     {}

func (m *DatabaseResponse) GetSuccess() isDatabaseResponse_Success {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *DatabaseResponse) GetHeader() *DatabaseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DatabaseResponse) GetRedirect() *DatabaseRedirectResponse {
	if x, ok := m.GetSuccess().(*DatabaseResponse_Redirect); ok {
		return x.Redirect
	}
	return nil
}

func (m *DatabaseResponse) GetResp() *DatabaseResponseResponse {
	if x, ok := m.GetSuccess().(*DatabaseResponse_Resp); ok {
		return x.Resp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DatabaseResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DatabaseResponse_OneofMarshaler, _DatabaseResponse_OneofUnmarshaler, _DatabaseResponse_OneofSizer, []interface{}{
		(*DatabaseResponse_Redirect)(nil),
		(*DatabaseResponse_Resp)(nil),
	}
}

func _DatabaseResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DatabaseResponse)
	// success
	switch x := m.Success.(type) {
	case *DatabaseResponse_Redirect:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Redirect); err != nil {
			return err
		}
	case *DatabaseResponse_Resp:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Resp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DatabaseResponse.Success has unexpected type %T", x)
	}
	return nil
}

func _DatabaseResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DatabaseResponse)
	switch tag {
	case 2: // success.redirect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseRedirectResponse)
		err := b.DecodeMessage(msg)
		m.Success = &DatabaseResponse_Redirect{msg}
		return true, err
	case 3: // success.resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatabaseResponseResponse)
		err := b.DecodeMessage(msg)
		m.Success = &DatabaseResponse_Resp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DatabaseResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DatabaseResponse)
	// success
	switch x := m.Success.(type) {
	case *DatabaseResponse_Redirect:
		s := proto.Size(x.Redirect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DatabaseResponse_Resp:
		s := proto.Size(x.Resp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DatabaseResponseResponse struct {
	Value                []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Has                  bool     `protobuf:"varint,5,opt,name=has,proto3" json:"has,omitempty"`
	Size                 int32    `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Error                string   `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Keys                 []string `protobuf:"bytes,8,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseResponseResponse) Reset()         { *m = DatabaseResponseResponse{} }
func (m *DatabaseResponseResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseResponseResponse) ProtoMessage()    {}
func (*DatabaseResponseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_database_31bcadf79436cc71, []int{9, 0}
}
func (m *DatabaseResponseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseResponseResponse.Unmarshal(m, b)
}
func (m *DatabaseResponseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseResponseResponse.Marshal(b, m, deterministic)
}
func (dst *DatabaseResponseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseResponseResponse.Merge(dst, src)
}
func (m *DatabaseResponseResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseResponseResponse.Size(m)
}
func (m *DatabaseResponseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseResponseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseResponseResponse proto.InternalMessageInfo

func (m *DatabaseResponseResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DatabaseResponseResponse) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

func (m *DatabaseResponseResponse) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DatabaseResponseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DatabaseResponseResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*DatabaseMsg)(nil), "pb.database_msg")
	proto.RegisterType((*DatabaseRedirectResponse)(nil), "pb.database_redirect_response")
	proto.RegisterType((*DatabaseHeader)(nil), "pb.database_header")
	proto.RegisterType((*DatabaseCreate)(nil), "pb.database_create")
	proto.RegisterType((*DatabaseRead)(nil), "pb.database_read")
	proto.RegisterType((*DatabaseUpdate)(nil), "pb.database_update")
	proto.RegisterType((*DatabaseDelete)(nil), "pb.database_delete")
	proto.RegisterType((*DatabaseHas)(nil), "pb.database_has")
	proto.RegisterType((*DatabaseEmpty)(nil), "pb.database_empty")
	proto.RegisterType((*DatabaseResponse)(nil), "pb.database_response")
	proto.RegisterType((*DatabaseResponseResponse)(nil), "pb.database_response.response")
}

func init() { proto.RegisterFile("database.proto", fileDescriptor_database_31bcadf79436cc71) }

var fileDescriptor_database_31bcadf79436cc71 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0xb3, 0xf9, 0xce, 0xe4, 0xa3, 0xa9, 0x41, 0x62, 0x55, 0x24, 0x58, 0x16, 0x10, 0x2b,
	0x21, 0x72, 0x00, 0x2e, 0x48, 0x9c, 0x7a, 0x4a, 0x2f, 0x08, 0x56, 0xe2, 0x1c, 0x79, 0xe3, 0x51,
	0x13, 0x35, 0xc9, 0x5a, 0xb6, 0x17, 0x29, 0xbc, 0x15, 0x2f, 0xc1, 0x03, 0xf1, 0x04, 0x68, 0x6c,
	0x27, 0x75, 0x3e, 0x04, 0xbd, 0x79, 0x3d, 0xbf, 0xf9, 0x77, 0xc6, 0xfd, 0xff, 0x03, 0x23, 0xc1,
	0x0d, 0x2f, 0xb8, 0xc6, 0x89, 0x54, 0xa5, 0x29, 0x59, 0x5d, 0x16, 0xe9, 0x9f, 0x3a, 0x0c, 0x76,
	0xd7, 0xb3, 0xb5, 0xbe, 0x65, 0x6f, 0xa1, 0xbd, 0x40, 0x2e, 0x50, 0xc5, 0xf5, 0x24, 0xca, 0xfa,
	0xef, 0x1f, 0x4d, 0x64, 0x31, 0xd9, 0x13, 0xae, 0x94, 0x7b, 0x84, 0xbd, 0x83, 0xf6, 0x5c, 0x21,
	0x37, 0x18, 0xc3, 0x19, 0xd8, 0x95, 0xa6, 0xb5, 0xdc, 0x43, 0xec, 0x0d, 0x34, 0x15, 0x72, 0x11,
	0xf7, 0x2d, 0x7c, 0x79, 0x00, 0x53, 0x61, 0x5a, 0xcb, 0x2d, 0x40, 0xba, 0x95, 0x14, 0xa4, 0x3b,
	0x38, 0xa3, 0xeb, 0x4a, 0xa4, 0xeb, 0x4e, 0x84, 0x0b, 0x5c, 0xa1, 0xc1, 0x78, 0x78, 0x06, 0x77,
	0x25, 0xc2, 0xdd, 0x89, 0xbd, 0x82, 0xc6, 0x82, 0xeb, 0x78, 0x64, 0xd9, 0xf1, 0xe1, 0x7e, 0x5c,
	0x4f, 0x6b, 0x39, 0x95, 0x59, 0x06, 0xcd, 0x3b, 0xdc, 0xea, 0xf8, 0xc2, 0x62, 0xec, 0x00, 0xc3,
	0xb5, 0x34, 0x5b, 0x9a, 0x96, 0x08, 0x22, 0xf5, 0xf2, 0x27, 0xc6, 0xe3, 0x7f, 0x91, 0x44, 0x5c,
	0xb7, 0xa0, 0xb1, 0xd6, 0xb7, 0xe9, 0xef, 0x08, 0xae, 0x82, 0xc5, 0xc5, 0x52, 0xe1, 0xdc, 0xcc,
	0x14, 0x6a, 0x59, 0x6e, 0x34, 0xb2, 0xa7, 0xd0, 0x5b, 0xd9, 0xf7, 0x9d, 0x2d, 0x45, 0x1c, 0x25,
	0x51, 0xd6, 0xcb, 0xbb, 0xee, 0xe2, 0x46, 0xb0, 0xe7, 0xd0, 0xf7, 0xc5, 0x0d, 0x5f, 0xa3, 0xfd,
	0x27, 0xf5, 0x72, 0x70, 0x57, 0x5f, 0xf8, 0x1a, 0x03, 0x60, 0x51, 0x6a, 0x13, 0x37, 0x42, 0x60,
	0x5a, 0x6a, 0x13, 0x00, 0xb2, 0x54, 0x26, 0x6e, 0x26, 0x51, 0x36, 0xdc, 0x01, 0x5f, 0x4b, 0x65,
	0x58, 0x06, 0xe3, 0x9d, 0x82, 0x31, 0xd2, 0x51, 0x2d, 0x4b, 0x8d, 0xbc, 0x8c, 0x31, 0x92, 0xc8,
	0xf4, 0x1b, 0x5c, 0x1c, 0x59, 0x83, 0x3d, 0x81, 0x8e, 0x28, 0x66, 0x55, 0xb5, 0x1f, 0xbd, 0x2d,
	0x8a, 0xef, 0xd5, 0x52, 0xb0, 0xd7, 0x30, 0x32, 0x8a, 0x6f, 0x34, 0x9f, 0x9b, 0x65, 0xb9, 0xa1,
	0xd5, 0x68, 0xf6, 0x66, 0x3e, 0x0c, 0x6e, 0x6f, 0x44, 0xfa, 0x29, 0x90, 0xf4, 0xb6, 0x19, 0x43,
	0xe3, 0x0e, 0xb7, 0x7e, 0x55, 0x3a, 0xb2, 0xc7, 0xd0, 0xfa, 0xc1, 0x57, 0x15, 0xda, 0xed, 0x06,
	0xb9, 0xfb, 0x48, 0x5f, 0xc0, 0xf0, 0xc0, 0x4e, 0xa7, 0x8d, 0x07, 0xea, 0xde, 0x3c, 0x0f, 0x55,
	0x7f, 0x19, 0xb4, 0x7a, 0x23, 0x9d, 0xea, 0x27, 0x41, 0x9a, 0xc8, 0x44, 0xa7, 0xc4, 0xf8, 0x3e,
	0x86, 0xce, 0x1c, 0xe9, 0xaf, 0x3a, 0x5c, 0x06, 0x73, 0x7b, 0x13, 0xdc, 0xe7, 0x30, 0xfa, 0x7f,
	0x0e, 0x3f, 0x43, 0x77, 0x67, 0x23, 0x1f, 0xdb, 0x67, 0x47, 0xe1, 0x3a, 0xf2, 0xd8, 0xb4, 0x96,
	0xef, 0x3b, 0xd8, 0x47, 0x8a, 0xa5, 0x96, 0x76, 0xdd, 0xd3, 0x4e, 0xd7, 0x30, 0x09, 0x3a, 0x2d,
	0x7d, 0x25, 0xe9, 0x6f, 0xfa, 0x61, 0xf7, 0x2f, 0xd6, 0x0c, 0x5e, 0x8c, 0x96, 0xa7, 0x9c, 0x91,
	0x75, 0xba, 0x2e, 0x53, 0xcc, 0x27, 0xa5, 0x9d, 0x44, 0x59, 0xcb, 0x65, 0x82, 0x7a, 0x51, 0xa9,
	0x52, 0xc5, 0x1d, 0xfb, 0x48, 0xee, 0x83, 0x48, 0x9b, 0xbe, 0x6e, 0xd2, 0xc8, 0x7a, 0x2e, 0x67,
	0xd7, 0x3d, 0xe8, 0xe8, 0x6a, 0x3e, 0x47, 0xad, 0x8b, 0xb6, 0xfd, 0x05, 0xfb, 0xf0, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xe1, 0x2d, 0x12, 0x7c, 0xd3, 0x04, 0x00, 0x00,
}
