// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audit.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuditMessage struct {
	// Types that are valid to be assigned to Msg:
	//	*AuditMessage_PbftCommit
	//	*AuditMessage_PrimaryStatus
	//	*AuditMessage_FailureDetected
	Msg                  isAuditMessage_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AuditMessage) Reset()         { *m = AuditMessage{} }
func (m *AuditMessage) String() string { return proto.CompactTextString(m) }
func (*AuditMessage) ProtoMessage()    {}
func (*AuditMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{0}
}

func (m *AuditMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditMessage.Unmarshal(m, b)
}
func (m *AuditMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditMessage.Marshal(b, m, deterministic)
}
func (m *AuditMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditMessage.Merge(m, src)
}
func (m *AuditMessage) XXX_Size() int {
	return xxx_messageInfo_AuditMessage.Size(m)
}
func (m *AuditMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuditMessage proto.InternalMessageInfo

type isAuditMessage_Msg interface {
	isAuditMessage_Msg()
}

type AuditMessage_PbftCommit struct {
	PbftCommit *PbftCommitNotification `protobuf:"bytes,1,opt,name=pbft_commit,json=pbftCommit,proto3,oneof"`
}

type AuditMessage_PrimaryStatus struct {
	PrimaryStatus *PrimaryStatus `protobuf:"bytes,2,opt,name=primary_status,json=primaryStatus,proto3,oneof"`
}

type AuditMessage_FailureDetected struct {
	FailureDetected *FailureDetected `protobuf:"bytes,3,opt,name=failure_detected,json=failureDetected,proto3,oneof"`
}

func (*AuditMessage_PbftCommit) isAuditMessage_Msg() {}

func (*AuditMessage_PrimaryStatus) isAuditMessage_Msg() {}

func (*AuditMessage_FailureDetected) isAuditMessage_Msg() {}

func (m *AuditMessage) GetMsg() isAuditMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *AuditMessage) GetPbftCommit() *PbftCommitNotification {
	if x, ok := m.GetMsg().(*AuditMessage_PbftCommit); ok {
		return x.PbftCommit
	}
	return nil
}

func (m *AuditMessage) GetPrimaryStatus() *PrimaryStatus {
	if x, ok := m.GetMsg().(*AuditMessage_PrimaryStatus); ok {
		return x.PrimaryStatus
	}
	return nil
}

func (m *AuditMessage) GetFailureDetected() *FailureDetected {
	if x, ok := m.GetMsg().(*AuditMessage_FailureDetected); ok {
		return x.FailureDetected
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AuditMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AuditMessage_PbftCommit)(nil),
		(*AuditMessage_PrimaryStatus)(nil),
		(*AuditMessage_FailureDetected)(nil),
	}
}

type LeaderStatus struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Leader               string   `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	CurrentLogIndex      uint64   `protobuf:"varint,3,opt,name=current_log_index,json=currentLogIndex,proto3" json:"current_log_index,omitempty"`
	CurrentCommitIndex   uint64   `protobuf:"varint,4,opt,name=current_commit_index,json=currentCommitIndex,proto3" json:"current_commit_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderStatus) Reset()         { *m = LeaderStatus{} }
func (m *LeaderStatus) String() string { return proto.CompactTextString(m) }
func (*LeaderStatus) ProtoMessage()    {}
func (*LeaderStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{1}
}

func (m *LeaderStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderStatus.Unmarshal(m, b)
}
func (m *LeaderStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderStatus.Marshal(b, m, deterministic)
}
func (m *LeaderStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderStatus.Merge(m, src)
}
func (m *LeaderStatus) XXX_Size() int {
	return xxx_messageInfo_LeaderStatus.Size(m)
}
func (m *LeaderStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderStatus proto.InternalMessageInfo

func (m *LeaderStatus) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LeaderStatus) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *LeaderStatus) GetCurrentLogIndex() uint64 {
	if m != nil {
		return m.CurrentLogIndex
	}
	return 0
}

func (m *LeaderStatus) GetCurrentCommitIndex() uint64 {
	if m != nil {
		return m.CurrentCommitIndex
	}
	return 0
}

type PrimaryStatus struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Primary              string   `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimaryStatus) Reset()         { *m = PrimaryStatus{} }
func (m *PrimaryStatus) String() string { return proto.CompactTextString(m) }
func (*PrimaryStatus) ProtoMessage()    {}
func (*PrimaryStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{2}
}

func (m *PrimaryStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryStatus.Unmarshal(m, b)
}
func (m *PrimaryStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryStatus.Marshal(b, m, deterministic)
}
func (m *PrimaryStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryStatus.Merge(m, src)
}
func (m *PrimaryStatus) XXX_Size() int {
	return xxx_messageInfo_PrimaryStatus.Size(m)
}
func (m *PrimaryStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryStatus proto.InternalMessageInfo

func (m *PrimaryStatus) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrimaryStatus) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

type PbftCommitNotification struct {
	SenderUuid           string   `protobuf:"bytes,1,opt,name=sender_uuid,json=senderUuid,proto3" json:"sender_uuid,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Operation            []byte   `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbftCommitNotification) Reset()         { *m = PbftCommitNotification{} }
func (m *PbftCommitNotification) String() string { return proto.CompactTextString(m) }
func (*PbftCommitNotification) ProtoMessage()    {}
func (*PbftCommitNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{3}
}

func (m *PbftCommitNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbftCommitNotification.Unmarshal(m, b)
}
func (m *PbftCommitNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbftCommitNotification.Marshal(b, m, deterministic)
}
func (m *PbftCommitNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbftCommitNotification.Merge(m, src)
}
func (m *PbftCommitNotification) XXX_Size() int {
	return xxx_messageInfo_PbftCommitNotification.Size(m)
}
func (m *PbftCommitNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_PbftCommitNotification.DiscardUnknown(m)
}

var xxx_messageInfo_PbftCommitNotification proto.InternalMessageInfo

func (m *PbftCommitNotification) GetSenderUuid() string {
	if m != nil {
		return m.SenderUuid
	}
	return ""
}

func (m *PbftCommitNotification) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *PbftCommitNotification) GetOperation() []byte {
	if m != nil {
		return m.Operation
	}
	return nil
}

type FailureDetected struct {
	SenderUuid           string   `protobuf:"bytes,1,opt,name=sender_uuid,json=senderUuid,proto3" json:"sender_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailureDetected) Reset()         { *m = FailureDetected{} }
func (m *FailureDetected) String() string { return proto.CompactTextString(m) }
func (*FailureDetected) ProtoMessage()    {}
func (*FailureDetected) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{4}
}

func (m *FailureDetected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailureDetected.Unmarshal(m, b)
}
func (m *FailureDetected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailureDetected.Marshal(b, m, deterministic)
}
func (m *FailureDetected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailureDetected.Merge(m, src)
}
func (m *FailureDetected) XXX_Size() int {
	return xxx_messageInfo_FailureDetected.Size(m)
}
func (m *FailureDetected) XXX_DiscardUnknown() {
	xxx_messageInfo_FailureDetected.DiscardUnknown(m)
}

var xxx_messageInfo_FailureDetected proto.InternalMessageInfo

func (m *FailureDetected) GetSenderUuid() string {
	if m != nil {
		return m.SenderUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*AuditMessage)(nil), "pb.audit_message")
	proto.RegisterType((*LeaderStatus)(nil), "pb.leader_status")
	proto.RegisterType((*PrimaryStatus)(nil), "pb.primary_status")
	proto.RegisterType((*PbftCommitNotification)(nil), "pb.pbft_commit_notification")
	proto.RegisterType((*FailureDetected)(nil), "pb.failure_detected")
}

func init() { proto.RegisterFile("audit.proto", fileDescriptor_5594839dd8e38a1b) }

var fileDescriptor_5594839dd8e38a1b = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x86, 0x9b, 0x36, 0xdb, 0x55, 0x27, 0xdb, 0x76, 0xd7, 0xaa, 0x56, 0x39, 0x54, 0xda, 0x55,
	0x2e, 0x20, 0x0e, 0x15, 0xa2, 0x47, 0x24, 0x10, 0x1f, 0x87, 0x22, 0x21, 0x0e, 0x46, 0x9c, 0xad,
	0x7c, 0x4c, 0x23, 0x4b, 0x4d, 0x1c, 0x1c, 0x9b, 0x8f, 0x2b, 0xff, 0x82, 0x5f, 0xc6, 0xdf, 0x41,
	0x99, 0x38, 0x02, 0x8a, 0x10, 0xb7, 0xf8, 0x79, 0xdf, 0x19, 0xbf, 0x33, 0x0e, 0x04, 0xb1, 0xcd,
	0xa4, 0x59, 0x54, 0x5a, 0x19, 0xc5, 0xfa, 0x55, 0x12, 0xbd, 0x78, 0x30, 0x26, 0x26, 0x0a, 0xac,
	0xeb, 0x38, 0x47, 0x76, 0x0c, 0x41, 0x95, 0xac, 0x8d, 0x48, 0x55, 0x51, 0x48, 0x13, 0x7a, 0xff,
	0xbd, 0xdd, 0xe0, 0x60, 0xbe, 0xa8, 0x92, 0xc5, 0x3b, 0x2c, 0x4a, 0x65, 0xe4, 0x5a, 0xa6, 0xb1,
	0x91, 0xaa, 0x5c, 0xf5, 0x38, 0x34, 0xda, 0x19, 0x49, 0xec, 0x10, 0x26, 0x95, 0x96, 0x45, 0xac,
	0x1f, 0x45, 0x6d, 0x62, 0x63, 0xeb, 0xb0, 0x4f, 0x3d, 0x18, 0xf5, 0xf8, 0xa0, 0xac, 0x7a, 0x7c,
	0xec, 0xc8, 0x35, 0x01, 0x76, 0x02, 0xbf, 0xd7, 0xb1, 0xdc, 0x58, 0x8d, 0x22, 0x43, 0x83, 0xa9,
	0xc1, 0x2c, 0x1c, 0x50, 0xf9, 0xac, 0x29, 0xdf, 0xd6, 0x56, 0x3d, 0x3e, 0x75, 0xec, 0xdc, 0xa1,
	0xd3, 0x1f, 0x30, 0x28, 0xea, 0x3c, 0x7a, 0xf6, 0x60, 0xbc, 0xc1, 0x38, 0x43, 0xed, 0x2e, 0x63,
	0x0c, 0x7c, 0x83, 0xba, 0xa0, 0x91, 0x7c, 0x4e, 0xdf, 0xec, 0x2f, 0x0c, 0x5b, 0x13, 0x85, 0x1c,
	0x71, 0x77, 0x62, 0x7b, 0xf0, 0x27, 0xb5, 0x5a, 0x63, 0x69, 0xc4, 0x46, 0xe5, 0x42, 0x96, 0x19,
	0x3e, 0x50, 0x10, 0x9f, 0x4f, 0x9d, 0x70, 0xa9, 0xf2, 0x8b, 0x06, 0xb3, 0x7d, 0x98, 0x75, 0x5e,
	0xb7, 0x9d, 0xd6, 0xee, 0x93, 0x9d, 0x39, 0xad, 0xdd, 0x0e, 0x55, 0x44, 0x47, 0xdb, 0x2b, 0x6a,
	0xb2, 0xdd, 0x49, 0xbc, 0xef, 0xb2, 0x35, 0xdf, 0x2c, 0x84, 0x9f, 0xce, 0xe5, 0xc2, 0x75, 0xc7,
	0xe8, 0xc9, 0x83, 0xf0, 0xab, 0xd7, 0x60, 0xff, 0x20, 0xa8, 0xb1, 0x6c, 0xe6, 0xb6, 0x56, 0x66,
	0xd4, 0x71, 0xc4, 0xa1, 0x45, 0x37, 0x56, 0x66, 0x6c, 0x07, 0xa6, 0x35, 0xde, 0x5a, 0x2c, 0x53,
	0x14, 0xa5, 0x2d, 0x12, 0x37, 0xbc, 0xcf, 0x27, 0x1d, 0xbe, 0x22, 0xca, 0xe6, 0x30, 0x52, 0x15,
	0x6a, 0x6a, 0x4b, 0xc3, 0xff, 0xe2, 0x6f, 0x20, 0x5a, 0x7e, 0x7e, 0xaa, 0x6f, 0xef, 0x4e, 0x86,
	0xf4, 0xeb, 0x2d, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x51, 0x59, 0x9d, 0x0e, 0x89, 0x02, 0x00,
	0x00,
}
