// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatabaseSubscriptionUpdateOperationType int32

const (
	DatabaseSubscriptionUpdate_UPDATE DatabaseSubscriptionUpdateOperationType = 0
	DatabaseSubscriptionUpdate_DELETE DatabaseSubscriptionUpdateOperationType = 1
)

var DatabaseSubscriptionUpdateOperationType_name = map[int32]string{
	0: "UPDATE",
	1: "DELETE",
}

var DatabaseSubscriptionUpdateOperationType_value = map[string]int32{
	"UPDATE": 0,
	"DELETE": 1,
}

func (x DatabaseSubscriptionUpdateOperationType) String() string {
	return proto.EnumName(DatabaseSubscriptionUpdateOperationType_name, int32(x))
}

func (DatabaseSubscriptionUpdateOperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{12, 0}
}

type DatabaseMsg struct {
	Header *DatabaseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*DatabaseMsg_Create
	//	*DatabaseMsg_Read
	//	*DatabaseMsg_Update
	//	*DatabaseMsg_Delete
	//	*DatabaseMsg_Has
	//	*DatabaseMsg_Keys
	//	*DatabaseMsg_Size
	//	*DatabaseMsg_Subscribe
	//	*DatabaseMsg_Unsubscribe
	//	*DatabaseMsg_Nullmsg
	//	*DatabaseMsg_CreateDb
	//	*DatabaseMsg_DeleteDb
	//	*DatabaseMsg_HasDb
	//	*DatabaseMsg_Writers
	//	*DatabaseMsg_AddWriters
	//	*DatabaseMsg_RemoveWriters
	//	*DatabaseMsg_QuickRead
	//	*DatabaseMsg_Expire
	//	*DatabaseMsg_Persist
	//	*DatabaseMsg_Ttl
	Msg                  isDatabaseMsg_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DatabaseMsg) Reset()         { *m = DatabaseMsg{} }
func (m *DatabaseMsg) String() string { return proto.CompactTextString(m) }
func (*DatabaseMsg) ProtoMessage()    {}
func (*DatabaseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{0}
}

func (m *DatabaseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseMsg.Unmarshal(m, b)
}
func (m *DatabaseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseMsg.Marshal(b, m, deterministic)
}
func (m *DatabaseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseMsg.Merge(m, src)
}
func (m *DatabaseMsg) XXX_Size() int {
	return xxx_messageInfo_DatabaseMsg.Size(m)
}
func (m *DatabaseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseMsg proto.InternalMessageInfo

func (m *DatabaseMsg) GetHeader() *DatabaseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type isDatabaseMsg_Msg interface {
	isDatabaseMsg_Msg()
}

type DatabaseMsg_Create struct {
	Create *DatabaseCreate `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type DatabaseMsg_Read struct {
	Read *DatabaseRead `protobuf:"bytes,3,opt,name=read,proto3,oneof"`
}

type DatabaseMsg_Update struct {
	Update *DatabaseUpdate `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

type DatabaseMsg_Delete struct {
	Delete *DatabaseDelete `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type DatabaseMsg_Has struct {
	Has *DatabaseHas `protobuf:"bytes,6,opt,name=has,proto3,oneof"`
}

type DatabaseMsg_Keys struct {
	Keys *DatabaseRequest `protobuf:"bytes,7,opt,name=keys,proto3,oneof"`
}

type DatabaseMsg_Size struct {
	Size *DatabaseRequest `protobuf:"bytes,8,opt,name=size,proto3,oneof"`
}

type DatabaseMsg_Subscribe struct {
	Subscribe *DatabaseSubscribe `protobuf:"bytes,9,opt,name=subscribe,proto3,oneof"`
}

type DatabaseMsg_Unsubscribe struct {
	Unsubscribe *DatabaseUnsubscribe `protobuf:"bytes,10,opt,name=unsubscribe,proto3,oneof"`
}

type DatabaseMsg_Nullmsg struct {
	Nullmsg *DatabaseNullmsg `protobuf:"bytes,11,opt,name=nullmsg,proto3,oneof"`
}

type DatabaseMsg_CreateDb struct {
	CreateDb *DatabaseRequest `protobuf:"bytes,12,opt,name=create_db,json=createDb,proto3,oneof"`
}

type DatabaseMsg_DeleteDb struct {
	DeleteDb *DatabaseRequest `protobuf:"bytes,13,opt,name=delete_db,json=deleteDb,proto3,oneof"`
}

type DatabaseMsg_HasDb struct {
	HasDb *DatabaseHasDb `protobuf:"bytes,14,opt,name=has_db,json=hasDb,proto3,oneof"`
}

type DatabaseMsg_Writers struct {
	Writers *DatabaseRequest `protobuf:"bytes,16,opt,name=writers,proto3,oneof"`
}

type DatabaseMsg_AddWriters struct {
	AddWriters *DatabaseWriters `protobuf:"bytes,17,opt,name=add_writers,json=addWriters,proto3,oneof"`
}

type DatabaseMsg_RemoveWriters struct {
	RemoveWriters *DatabaseWriters `protobuf:"bytes,18,opt,name=remove_writers,json=removeWriters,proto3,oneof"`
}

type DatabaseMsg_QuickRead struct {
	QuickRead *DatabaseRead `protobuf:"bytes,19,opt,name=quick_read,json=quickRead,proto3,oneof"`
}

type DatabaseMsg_Expire struct {
	Expire *DatabaseExpire `protobuf:"bytes,20,opt,name=expire,proto3,oneof"`
}

type DatabaseMsg_Persist struct {
	Persist *DatabaseRead `protobuf:"bytes,21,opt,name=persist,proto3,oneof"`
}

type DatabaseMsg_Ttl struct {
	Ttl *DatabaseRead `protobuf:"bytes,22,opt,name=ttl,proto3,oneof"`
}

func (*DatabaseMsg_Create) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Read) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Update) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Delete) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Has) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Keys) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Size) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Subscribe) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Unsubscribe) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Nullmsg) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_CreateDb) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_DeleteDb) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_HasDb) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Writers) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_AddWriters) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_RemoveWriters) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_QuickRead) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Expire) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Persist) isDatabaseMsg_Msg() {}

func (*DatabaseMsg_Ttl) isDatabaseMsg_Msg() {}

func (m *DatabaseMsg) GetMsg() isDatabaseMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *DatabaseMsg) GetCreate() *DatabaseCreate {
	if x, ok := m.GetMsg().(*DatabaseMsg_Create); ok {
		return x.Create
	}
	return nil
}

func (m *DatabaseMsg) GetRead() *DatabaseRead {
	if x, ok := m.GetMsg().(*DatabaseMsg_Read); ok {
		return x.Read
	}
	return nil
}

func (m *DatabaseMsg) GetUpdate() *DatabaseUpdate {
	if x, ok := m.GetMsg().(*DatabaseMsg_Update); ok {
		return x.Update
	}
	return nil
}

func (m *DatabaseMsg) GetDelete() *DatabaseDelete {
	if x, ok := m.GetMsg().(*DatabaseMsg_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *DatabaseMsg) GetHas() *DatabaseHas {
	if x, ok := m.GetMsg().(*DatabaseMsg_Has); ok {
		return x.Has
	}
	return nil
}

func (m *DatabaseMsg) GetKeys() *DatabaseRequest {
	if x, ok := m.GetMsg().(*DatabaseMsg_Keys); ok {
		return x.Keys
	}
	return nil
}

func (m *DatabaseMsg) GetSize() *DatabaseRequest {
	if x, ok := m.GetMsg().(*DatabaseMsg_Size); ok {
		return x.Size
	}
	return nil
}

func (m *DatabaseMsg) GetSubscribe() *DatabaseSubscribe {
	if x, ok := m.GetMsg().(*DatabaseMsg_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *DatabaseMsg) GetUnsubscribe() *DatabaseUnsubscribe {
	if x, ok := m.GetMsg().(*DatabaseMsg_Unsubscribe); ok {
		return x.Unsubscribe
	}
	return nil
}

func (m *DatabaseMsg) GetNullmsg() *DatabaseNullmsg {
	if x, ok := m.GetMsg().(*DatabaseMsg_Nullmsg); ok {
		return x.Nullmsg
	}
	return nil
}

func (m *DatabaseMsg) GetCreateDb() *DatabaseRequest {
	if x, ok := m.GetMsg().(*DatabaseMsg_CreateDb); ok {
		return x.CreateDb
	}
	return nil
}

func (m *DatabaseMsg) GetDeleteDb() *DatabaseRequest {
	if x, ok := m.GetMsg().(*DatabaseMsg_DeleteDb); ok {
		return x.DeleteDb
	}
	return nil
}

func (m *DatabaseMsg) GetHasDb() *DatabaseHasDb {
	if x, ok := m.GetMsg().(*DatabaseMsg_HasDb); ok {
		return x.HasDb
	}
	return nil
}

func (m *DatabaseMsg) GetWriters() *DatabaseRequest {
	if x, ok := m.GetMsg().(*DatabaseMsg_Writers); ok {
		return x.Writers
	}
	return nil
}

func (m *DatabaseMsg) GetAddWriters() *DatabaseWriters {
	if x, ok := m.GetMsg().(*DatabaseMsg_AddWriters); ok {
		return x.AddWriters
	}
	return nil
}

func (m *DatabaseMsg) GetRemoveWriters() *DatabaseWriters {
	if x, ok := m.GetMsg().(*DatabaseMsg_RemoveWriters); ok {
		return x.RemoveWriters
	}
	return nil
}

func (m *DatabaseMsg) GetQuickRead() *DatabaseRead {
	if x, ok := m.GetMsg().(*DatabaseMsg_QuickRead); ok {
		return x.QuickRead
	}
	return nil
}

func (m *DatabaseMsg) GetExpire() *DatabaseExpire {
	if x, ok := m.GetMsg().(*DatabaseMsg_Expire); ok {
		return x.Expire
	}
	return nil
}

func (m *DatabaseMsg) GetPersist() *DatabaseRead {
	if x, ok := m.GetMsg().(*DatabaseMsg_Persist); ok {
		return x.Persist
	}
	return nil
}

func (m *DatabaseMsg) GetTtl() *DatabaseRead {
	if x, ok := m.GetMsg().(*DatabaseMsg_Ttl); ok {
		return x.Ttl
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DatabaseMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DatabaseMsg_Create)(nil),
		(*DatabaseMsg_Read)(nil),
		(*DatabaseMsg_Update)(nil),
		(*DatabaseMsg_Delete)(nil),
		(*DatabaseMsg_Has)(nil),
		(*DatabaseMsg_Keys)(nil),
		(*DatabaseMsg_Size)(nil),
		(*DatabaseMsg_Subscribe)(nil),
		(*DatabaseMsg_Unsubscribe)(nil),
		(*DatabaseMsg_Nullmsg)(nil),
		(*DatabaseMsg_CreateDb)(nil),
		(*DatabaseMsg_DeleteDb)(nil),
		(*DatabaseMsg_HasDb)(nil),
		(*DatabaseMsg_Writers)(nil),
		(*DatabaseMsg_AddWriters)(nil),
		(*DatabaseMsg_RemoveWriters)(nil),
		(*DatabaseMsg_QuickRead)(nil),
		(*DatabaseMsg_Expire)(nil),
		(*DatabaseMsg_Persist)(nil),
		(*DatabaseMsg_Ttl)(nil),
	}
}

type DatabaseHeader struct {
	DbUuid               string   `protobuf:"bytes,1,opt,name=db_uuid,json=dbUuid,proto3" json:"db_uuid,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PointOfContact       string   `protobuf:"bytes,3,opt,name=point_of_contact,json=pointOfContact,proto3" json:"point_of_contact,omitempty"`
	RequestHash          []byte   `protobuf:"bytes,4,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHeader) Reset()         { *m = DatabaseHeader{} }
func (m *DatabaseHeader) String() string { return proto.CompactTextString(m) }
func (*DatabaseHeader) ProtoMessage()    {}
func (*DatabaseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{1}
}

func (m *DatabaseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHeader.Unmarshal(m, b)
}
func (m *DatabaseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHeader.Marshal(b, m, deterministic)
}
func (m *DatabaseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHeader.Merge(m, src)
}
func (m *DatabaseHeader) XXX_Size() int {
	return xxx_messageInfo_DatabaseHeader.Size(m)
}
func (m *DatabaseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHeader proto.InternalMessageInfo

func (m *DatabaseHeader) GetDbUuid() string {
	if m != nil {
		return m.DbUuid
	}
	return ""
}

func (m *DatabaseHeader) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DatabaseHeader) GetPointOfContact() string {
	if m != nil {
		return m.PointOfContact
	}
	return ""
}

func (m *DatabaseHeader) GetRequestHash() []byte {
	if m != nil {
		return m.RequestHash
	}
	return nil
}

type DatabaseCreate struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expire               uint64   `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseCreate) Reset()         { *m = DatabaseCreate{} }
func (m *DatabaseCreate) String() string { return proto.CompactTextString(m) }
func (*DatabaseCreate) ProtoMessage()    {}
func (*DatabaseCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{2}
}

func (m *DatabaseCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseCreate.Unmarshal(m, b)
}
func (m *DatabaseCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseCreate.Marshal(b, m, deterministic)
}
func (m *DatabaseCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseCreate.Merge(m, src)
}
func (m *DatabaseCreate) XXX_Size() int {
	return xxx_messageInfo_DatabaseCreate.Size(m)
}
func (m *DatabaseCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseCreate.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseCreate proto.InternalMessageInfo

func (m *DatabaseCreate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseCreate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DatabaseCreate) GetExpire() uint64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type DatabaseRead struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseRead) Reset()         { *m = DatabaseRead{} }
func (m *DatabaseRead) String() string { return proto.CompactTextString(m) }
func (*DatabaseRead) ProtoMessage()    {}
func (*DatabaseRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{3}
}

func (m *DatabaseRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseRead.Unmarshal(m, b)
}
func (m *DatabaseRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseRead.Marshal(b, m, deterministic)
}
func (m *DatabaseRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseRead.Merge(m, src)
}
func (m *DatabaseRead) XXX_Size() int {
	return xxx_messageInfo_DatabaseRead.Size(m)
}
func (m *DatabaseRead) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseRead.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseRead proto.InternalMessageInfo

func (m *DatabaseRead) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseUpdate struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expire               uint64   `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseUpdate) Reset()         { *m = DatabaseUpdate{} }
func (m *DatabaseUpdate) String() string { return proto.CompactTextString(m) }
func (*DatabaseUpdate) ProtoMessage()    {}
func (*DatabaseUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{4}
}

func (m *DatabaseUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseUpdate.Unmarshal(m, b)
}
func (m *DatabaseUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseUpdate.Marshal(b, m, deterministic)
}
func (m *DatabaseUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseUpdate.Merge(m, src)
}
func (m *DatabaseUpdate) XXX_Size() int {
	return xxx_messageInfo_DatabaseUpdate.Size(m)
}
func (m *DatabaseUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseUpdate proto.InternalMessageInfo

func (m *DatabaseUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseUpdate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DatabaseUpdate) GetExpire() uint64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type DatabaseExpire struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expire               uint64   `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseExpire) Reset()         { *m = DatabaseExpire{} }
func (m *DatabaseExpire) String() string { return proto.CompactTextString(m) }
func (*DatabaseExpire) ProtoMessage()    {}
func (*DatabaseExpire) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{5}
}

func (m *DatabaseExpire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseExpire.Unmarshal(m, b)
}
func (m *DatabaseExpire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseExpire.Marshal(b, m, deterministic)
}
func (m *DatabaseExpire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseExpire.Merge(m, src)
}
func (m *DatabaseExpire) XXX_Size() int {
	return xxx_messageInfo_DatabaseExpire.Size(m)
}
func (m *DatabaseExpire) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseExpire.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseExpire proto.InternalMessageInfo

func (m *DatabaseExpire) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseExpire) GetExpire() uint64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type DatabaseDelete struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseDelete) Reset()         { *m = DatabaseDelete{} }
func (m *DatabaseDelete) String() string { return proto.CompactTextString(m) }
func (*DatabaseDelete) ProtoMessage()    {}
func (*DatabaseDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{6}
}

func (m *DatabaseDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseDelete.Unmarshal(m, b)
}
func (m *DatabaseDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseDelete.Marshal(b, m, deterministic)
}
func (m *DatabaseDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseDelete.Merge(m, src)
}
func (m *DatabaseDelete) XXX_Size() int {
	return xxx_messageInfo_DatabaseDelete.Size(m)
}
func (m *DatabaseDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseDelete.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseDelete proto.InternalMessageInfo

func (m *DatabaseDelete) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseSubscribe struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseSubscribe) Reset()         { *m = DatabaseSubscribe{} }
func (m *DatabaseSubscribe) String() string { return proto.CompactTextString(m) }
func (*DatabaseSubscribe) ProtoMessage()    {}
func (*DatabaseSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{7}
}

func (m *DatabaseSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseSubscribe.Unmarshal(m, b)
}
func (m *DatabaseSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseSubscribe.Marshal(b, m, deterministic)
}
func (m *DatabaseSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseSubscribe.Merge(m, src)
}
func (m *DatabaseSubscribe) XXX_Size() int {
	return xxx_messageInfo_DatabaseSubscribe.Size(m)
}
func (m *DatabaseSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseSubscribe proto.InternalMessageInfo

func (m *DatabaseSubscribe) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseUnsubscribe struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseUnsubscribe) Reset()         { *m = DatabaseUnsubscribe{} }
func (m *DatabaseUnsubscribe) String() string { return proto.CompactTextString(m) }
func (*DatabaseUnsubscribe) ProtoMessage()    {}
func (*DatabaseUnsubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{8}
}

func (m *DatabaseUnsubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseUnsubscribe.Unmarshal(m, b)
}
func (m *DatabaseUnsubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseUnsubscribe.Marshal(b, m, deterministic)
}
func (m *DatabaseUnsubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseUnsubscribe.Merge(m, src)
}
func (m *DatabaseUnsubscribe) XXX_Size() int {
	return xxx_messageInfo_DatabaseUnsubscribe.Size(m)
}
func (m *DatabaseUnsubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseUnsubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseUnsubscribe proto.InternalMessageInfo

func (m *DatabaseUnsubscribe) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseUnsubscribe) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type DatabaseHas struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHas) Reset()         { *m = DatabaseHas{} }
func (m *DatabaseHas) String() string { return proto.CompactTextString(m) }
func (*DatabaseHas) ProtoMessage()    {}
func (*DatabaseHas) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{9}
}

func (m *DatabaseHas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHas.Unmarshal(m, b)
}
func (m *DatabaseHas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHas.Marshal(b, m, deterministic)
}
func (m *DatabaseHas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHas.Merge(m, src)
}
func (m *DatabaseHas) XXX_Size() int {
	return xxx_messageInfo_DatabaseHas.Size(m)
}
func (m *DatabaseHas) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHas.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHas proto.InternalMessageInfo

func (m *DatabaseHas) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DatabaseHasDb struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHasDb) Reset()         { *m = DatabaseHasDb{} }
func (m *DatabaseHasDb) String() string { return proto.CompactTextString(m) }
func (*DatabaseHasDb) ProtoMessage()    {}
func (*DatabaseHasDb) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{10}
}

func (m *DatabaseHasDb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHasDb.Unmarshal(m, b)
}
func (m *DatabaseHasDb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHasDb.Marshal(b, m, deterministic)
}
func (m *DatabaseHasDb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHasDb.Merge(m, src)
}
func (m *DatabaseHasDb) XXX_Size() int {
	return xxx_messageInfo_DatabaseHasDb.Size(m)
}
func (m *DatabaseHasDb) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHasDb.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHasDb proto.InternalMessageInfo

type DatabaseWriters struct {
	Writers              []string `protobuf:"bytes,1,rep,name=writers,proto3" json:"writers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseWriters) Reset()         { *m = DatabaseWriters{} }
func (m *DatabaseWriters) String() string { return proto.CompactTextString(m) }
func (*DatabaseWriters) ProtoMessage()    {}
func (*DatabaseWriters) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{11}
}

func (m *DatabaseWriters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseWriters.Unmarshal(m, b)
}
func (m *DatabaseWriters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseWriters.Marshal(b, m, deterministic)
}
func (m *DatabaseWriters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseWriters.Merge(m, src)
}
func (m *DatabaseWriters) XXX_Size() int {
	return xxx_messageInfo_DatabaseWriters.Size(m)
}
func (m *DatabaseWriters) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseWriters.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseWriters proto.InternalMessageInfo

func (m *DatabaseWriters) GetWriters() []string {
	if m != nil {
		return m.Writers
	}
	return nil
}

type DatabaseSubscriptionUpdate struct {
	Key                  string                                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte                                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operation            DatabaseSubscriptionUpdateOperationType `protobuf:"varint,3,opt,name=operation,proto3,enum=pb.DatabaseSubscriptionUpdateOperationType" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *DatabaseSubscriptionUpdate) Reset()         { *m = DatabaseSubscriptionUpdate{} }
func (m *DatabaseSubscriptionUpdate) String() string { return proto.CompactTextString(m) }
func (*DatabaseSubscriptionUpdate) ProtoMessage()    {}
func (*DatabaseSubscriptionUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{12}
}

func (m *DatabaseSubscriptionUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseSubscriptionUpdate.Unmarshal(m, b)
}
func (m *DatabaseSubscriptionUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseSubscriptionUpdate.Marshal(b, m, deterministic)
}
func (m *DatabaseSubscriptionUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseSubscriptionUpdate.Merge(m, src)
}
func (m *DatabaseSubscriptionUpdate) XXX_Size() int {
	return xxx_messageInfo_DatabaseSubscriptionUpdate.Size(m)
}
func (m *DatabaseSubscriptionUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseSubscriptionUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseSubscriptionUpdate proto.InternalMessageInfo

func (m *DatabaseSubscriptionUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseSubscriptionUpdate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DatabaseSubscriptionUpdate) GetOperation() DatabaseSubscriptionUpdateOperationType {
	if m != nil {
		return m.Operation
	}
	return DatabaseSubscriptionUpdate_UPDATE
}

type DatabaseRedirectResponse struct {
	LeaderId             string   `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderName           string   `protobuf:"bytes,2,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderHost           string   `protobuf:"bytes,3,opt,name=leader_host,json=leaderHost,proto3" json:"leader_host,omitempty"`
	LeaderPort           uint32   `protobuf:"varint,4,opt,name=leader_port,json=leaderPort,proto3" json:"leader_port,omitempty"`
	LeaderHttpPort       uint32   `protobuf:"varint,5,opt,name=leader_http_port,json=leaderHttpPort,proto3" json:"leader_http_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseRedirectResponse) Reset()         { *m = DatabaseRedirectResponse{} }
func (m *DatabaseRedirectResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseRedirectResponse) ProtoMessage()    {}
func (*DatabaseRedirectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{13}
}

func (m *DatabaseRedirectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseRedirectResponse.Unmarshal(m, b)
}
func (m *DatabaseRedirectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseRedirectResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseRedirectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseRedirectResponse.Merge(m, src)
}
func (m *DatabaseRedirectResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseRedirectResponse.Size(m)
}
func (m *DatabaseRedirectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseRedirectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseRedirectResponse proto.InternalMessageInfo

func (m *DatabaseRedirectResponse) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *DatabaseRedirectResponse) GetLeaderName() string {
	if m != nil {
		return m.LeaderName
	}
	return ""
}

func (m *DatabaseRedirectResponse) GetLeaderHost() string {
	if m != nil {
		return m.LeaderHost
	}
	return ""
}

func (m *DatabaseRedirectResponse) GetLeaderPort() uint32 {
	if m != nil {
		return m.LeaderPort
	}
	return 0
}

func (m *DatabaseRedirectResponse) GetLeaderHttpPort() uint32 {
	if m != nil {
		return m.LeaderHttpPort
	}
	return 0
}

type DatabaseHasResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Has                  bool     `protobuf:"varint,2,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHasResponse) Reset()         { *m = DatabaseHasResponse{} }
func (m *DatabaseHasResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseHasResponse) ProtoMessage()    {}
func (*DatabaseHasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{14}
}

func (m *DatabaseHasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHasResponse.Unmarshal(m, b)
}
func (m *DatabaseHasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHasResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseHasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHasResponse.Merge(m, src)
}
func (m *DatabaseHasResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseHasResponse.Size(m)
}
func (m *DatabaseHasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHasResponse proto.InternalMessageInfo

func (m *DatabaseHasResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseHasResponse) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

type DatabaseHasDbResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Has                  bool     `protobuf:"varint,2,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseHasDbResponse) Reset()         { *m = DatabaseHasDbResponse{} }
func (m *DatabaseHasDbResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseHasDbResponse) ProtoMessage()    {}
func (*DatabaseHasDbResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{15}
}

func (m *DatabaseHasDbResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseHasDbResponse.Unmarshal(m, b)
}
func (m *DatabaseHasDbResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseHasDbResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseHasDbResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseHasDbResponse.Merge(m, src)
}
func (m *DatabaseHasDbResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseHasDbResponse.Size(m)
}
func (m *DatabaseHasDbResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseHasDbResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseHasDbResponse proto.InternalMessageInfo

func (m *DatabaseHasDbResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DatabaseHasDbResponse) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

type DatabaseKeysResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseKeysResponse) Reset()         { *m = DatabaseKeysResponse{} }
func (m *DatabaseKeysResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseKeysResponse) ProtoMessage()    {}
func (*DatabaseKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{16}
}

func (m *DatabaseKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseKeysResponse.Unmarshal(m, b)
}
func (m *DatabaseKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseKeysResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseKeysResponse.Merge(m, src)
}
func (m *DatabaseKeysResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseKeysResponse.Size(m)
}
func (m *DatabaseKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseKeysResponse proto.InternalMessageInfo

func (m *DatabaseKeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type DatabaseReadResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseReadResponse) Reset()         { *m = DatabaseReadResponse{} }
func (m *DatabaseReadResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseReadResponse) ProtoMessage()    {}
func (*DatabaseReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{17}
}

func (m *DatabaseReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseReadResponse.Unmarshal(m, b)
}
func (m *DatabaseReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseReadResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseReadResponse.Merge(m, src)
}
func (m *DatabaseReadResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseReadResponse.Size(m)
}
func (m *DatabaseReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseReadResponse proto.InternalMessageInfo

func (m *DatabaseReadResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseReadResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DatabaseQuickReadResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseQuickReadResponse) Reset()         { *m = DatabaseQuickReadResponse{} }
func (m *DatabaseQuickReadResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseQuickReadResponse) ProtoMessage()    {}
func (*DatabaseQuickReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{18}
}

func (m *DatabaseQuickReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseQuickReadResponse.Unmarshal(m, b)
}
func (m *DatabaseQuickReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseQuickReadResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseQuickReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseQuickReadResponse.Merge(m, src)
}
func (m *DatabaseQuickReadResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseQuickReadResponse.Size(m)
}
func (m *DatabaseQuickReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseQuickReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseQuickReadResponse proto.InternalMessageInfo

func (m *DatabaseQuickReadResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseQuickReadResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DatabaseQuickReadResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DatabaseSizeResponse struct {
	Bytes                int32    `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Keys                 int32    `protobuf:"varint,2,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseSizeResponse) Reset()         { *m = DatabaseSizeResponse{} }
func (m *DatabaseSizeResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseSizeResponse) ProtoMessage()    {}
func (*DatabaseSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{19}
}

func (m *DatabaseSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseSizeResponse.Unmarshal(m, b)
}
func (m *DatabaseSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseSizeResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseSizeResponse.Merge(m, src)
}
func (m *DatabaseSizeResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseSizeResponse.Size(m)
}
func (m *DatabaseSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseSizeResponse proto.InternalMessageInfo

func (m *DatabaseSizeResponse) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *DatabaseSizeResponse) GetKeys() int32 {
	if m != nil {
		return m.Keys
	}
	return 0
}

type DatabaseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseRequest) Reset()         { *m = DatabaseRequest{} }
func (m *DatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*DatabaseRequest) ProtoMessage()    {}
func (*DatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{20}
}

func (m *DatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseRequest.Unmarshal(m, b)
}
func (m *DatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseRequest.Marshal(b, m, deterministic)
}
func (m *DatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseRequest.Merge(m, src)
}
func (m *DatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_DatabaseRequest.Size(m)
}
func (m *DatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseRequest proto.InternalMessageInfo

type DatabaseWritersResponse struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Writers              []string `protobuf:"bytes,2,rep,name=writers,proto3" json:"writers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseWritersResponse) Reset()         { *m = DatabaseWritersResponse{} }
func (m *DatabaseWritersResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseWritersResponse) ProtoMessage()    {}
func (*DatabaseWritersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{21}
}

func (m *DatabaseWritersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseWritersResponse.Unmarshal(m, b)
}
func (m *DatabaseWritersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseWritersResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseWritersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseWritersResponse.Merge(m, src)
}
func (m *DatabaseWritersResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseWritersResponse.Size(m)
}
func (m *DatabaseWritersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseWritersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseWritersResponse proto.InternalMessageInfo

func (m *DatabaseWritersResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DatabaseWritersResponse) GetWriters() []string {
	if m != nil {
		return m.Writers
	}
	return nil
}

type DatabaseTtlResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ttl                  uint64   `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseTtlResponse) Reset()         { *m = DatabaseTtlResponse{} }
func (m *DatabaseTtlResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseTtlResponse) ProtoMessage()    {}
func (*DatabaseTtlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{22}
}

func (m *DatabaseTtlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseTtlResponse.Unmarshal(m, b)
}
func (m *DatabaseTtlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseTtlResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseTtlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseTtlResponse.Merge(m, src)
}
func (m *DatabaseTtlResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseTtlResponse.Size(m)
}
func (m *DatabaseTtlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseTtlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseTtlResponse proto.InternalMessageInfo

func (m *DatabaseTtlResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DatabaseTtlResponse) GetTtl() uint64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type DatabaseError struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseError) Reset()         { *m = DatabaseError{} }
func (m *DatabaseError) String() string { return proto.CompactTextString(m) }
func (*DatabaseError) ProtoMessage()    {}
func (*DatabaseError) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{23}
}

func (m *DatabaseError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseError.Unmarshal(m, b)
}
func (m *DatabaseError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseError.Marshal(b, m, deterministic)
}
func (m *DatabaseError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseError.Merge(m, src)
}
func (m *DatabaseError) XXX_Size() int {
	return xxx_messageInfo_DatabaseError.Size(m)
}
func (m *DatabaseError) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseError.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseError proto.InternalMessageInfo

func (m *DatabaseError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DatabaseResponse struct {
	Header *DatabaseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*DatabaseResponse_Redirect
	//	*DatabaseResponse_SubscriptionUpdate
	//	*DatabaseResponse_Read
	//	*DatabaseResponse_QuickRead
	//	*DatabaseResponse_Has
	//	*DatabaseResponse_Keys
	//	*DatabaseResponse_Size
	//	*DatabaseResponse_Error
	//	*DatabaseResponse_HasDb
	//	*DatabaseResponse_Writers
	Response             isDatabaseResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DatabaseResponse) Reset()         { *m = DatabaseResponse{} }
func (m *DatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseResponse) ProtoMessage()    {}
func (*DatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{24}
}

func (m *DatabaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseResponse.Unmarshal(m, b)
}
func (m *DatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseResponse.Merge(m, src)
}
func (m *DatabaseResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseResponse.Size(m)
}
func (m *DatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseResponse proto.InternalMessageInfo

func (m *DatabaseResponse) GetHeader() *DatabaseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type isDatabaseResponse_Response interface {
	isDatabaseResponse_Response()
}

type DatabaseResponse_Redirect struct {
	Redirect *DatabaseRedirectResponse `protobuf:"bytes,2,opt,name=redirect,proto3,oneof"`
}

type DatabaseResponse_SubscriptionUpdate struct {
	SubscriptionUpdate *DatabaseSubscriptionUpdate `protobuf:"bytes,3,opt,name=subscription_update,json=subscriptionUpdate,proto3,oneof"`
}

type DatabaseResponse_Read struct {
	Read *DatabaseReadResponse `protobuf:"bytes,4,opt,name=read,proto3,oneof"`
}

type DatabaseResponse_QuickRead struct {
	QuickRead *DatabaseQuickReadResponse `protobuf:"bytes,5,opt,name=quick_read,json=quickRead,proto3,oneof"`
}

type DatabaseResponse_Has struct {
	Has *DatabaseHasResponse `protobuf:"bytes,6,opt,name=has,proto3,oneof"`
}

type DatabaseResponse_Keys struct {
	Keys *DatabaseKeysResponse `protobuf:"bytes,7,opt,name=keys,proto3,oneof"`
}

type DatabaseResponse_Size struct {
	Size *DatabaseSizeResponse `protobuf:"bytes,8,opt,name=size,proto3,oneof"`
}

type DatabaseResponse_Error struct {
	Error *DatabaseError `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

type DatabaseResponse_HasDb struct {
	HasDb *DatabaseHasDbResponse `protobuf:"bytes,10,opt,name=has_db,json=hasDb,proto3,oneof"`
}

type DatabaseResponse_Writers struct {
	Writers *DatabaseWritersResponse `protobuf:"bytes,11,opt,name=writers,proto3,oneof"`
}

func (*DatabaseResponse_Redirect) isDatabaseResponse_Response() {}

func (*DatabaseResponse_SubscriptionUpdate) isDatabaseResponse_Response() {}

func (*DatabaseResponse_Read) isDatabaseResponse_Response() {}

func (*DatabaseResponse_QuickRead) isDatabaseResponse_Response() {}

func (*DatabaseResponse_Has) isDatabaseResponse_Response() {}

func (*DatabaseResponse_Keys) isDatabaseResponse_Response() {}

func (*DatabaseResponse_Size) isDatabaseResponse_Response() {}

func (*DatabaseResponse_Error) isDatabaseResponse_Response() {}

func (*DatabaseResponse_HasDb) isDatabaseResponse_Response() {}

func (*DatabaseResponse_Writers) isDatabaseResponse_Response() {}

func (m *DatabaseResponse) GetResponse() isDatabaseResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *DatabaseResponse) GetRedirect() *DatabaseRedirectResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_Redirect); ok {
		return x.Redirect
	}
	return nil
}

func (m *DatabaseResponse) GetSubscriptionUpdate() *DatabaseSubscriptionUpdate {
	if x, ok := m.GetResponse().(*DatabaseResponse_SubscriptionUpdate); ok {
		return x.SubscriptionUpdate
	}
	return nil
}

func (m *DatabaseResponse) GetRead() *DatabaseReadResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_Read); ok {
		return x.Read
	}
	return nil
}

func (m *DatabaseResponse) GetQuickRead() *DatabaseQuickReadResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_QuickRead); ok {
		return x.QuickRead
	}
	return nil
}

func (m *DatabaseResponse) GetHas() *DatabaseHasResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_Has); ok {
		return x.Has
	}
	return nil
}

func (m *DatabaseResponse) GetKeys() *DatabaseKeysResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_Keys); ok {
		return x.Keys
	}
	return nil
}

func (m *DatabaseResponse) GetSize() *DatabaseSizeResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_Size); ok {
		return x.Size
	}
	return nil
}

func (m *DatabaseResponse) GetError() *DatabaseError {
	if x, ok := m.GetResponse().(*DatabaseResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *DatabaseResponse) GetHasDb() *DatabaseHasDbResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_HasDb); ok {
		return x.HasDb
	}
	return nil
}

func (m *DatabaseResponse) GetWriters() *DatabaseWritersResponse {
	if x, ok := m.GetResponse().(*DatabaseResponse_Writers); ok {
		return x.Writers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DatabaseResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DatabaseResponse_Redirect)(nil),
		(*DatabaseResponse_SubscriptionUpdate)(nil),
		(*DatabaseResponse_Read)(nil),
		(*DatabaseResponse_QuickRead)(nil),
		(*DatabaseResponse_Has)(nil),
		(*DatabaseResponse_Keys)(nil),
		(*DatabaseResponse_Size)(nil),
		(*DatabaseResponse_Error)(nil),
		(*DatabaseResponse_HasDb)(nil),
		(*DatabaseResponse_Writers)(nil),
	}
}

type DatabaseNullmsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseNullmsg) Reset()         { *m = DatabaseNullmsg{} }
func (m *DatabaseNullmsg) String() string { return proto.CompactTextString(m) }
func (*DatabaseNullmsg) ProtoMessage()    {}
func (*DatabaseNullmsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{25}
}

func (m *DatabaseNullmsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseNullmsg.Unmarshal(m, b)
}
func (m *DatabaseNullmsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseNullmsg.Marshal(b, m, deterministic)
}
func (m *DatabaseNullmsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseNullmsg.Merge(m, src)
}
func (m *DatabaseNullmsg) XXX_Size() int {
	return xxx_messageInfo_DatabaseNullmsg.Size(m)
}
func (m *DatabaseNullmsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseNullmsg.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseNullmsg proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.DatabaseSubscriptionUpdateOperationType", DatabaseSubscriptionUpdateOperationType_name, DatabaseSubscriptionUpdateOperationType_value)
	proto.RegisterType((*DatabaseMsg)(nil), "pb.database_msg")
	proto.RegisterType((*DatabaseHeader)(nil), "pb.database_header")
	proto.RegisterType((*DatabaseCreate)(nil), "pb.database_create")
	proto.RegisterType((*DatabaseRead)(nil), "pb.database_read")
	proto.RegisterType((*DatabaseUpdate)(nil), "pb.database_update")
	proto.RegisterType((*DatabaseExpire)(nil), "pb.database_expire")
	proto.RegisterType((*DatabaseDelete)(nil), "pb.database_delete")
	proto.RegisterType((*DatabaseSubscribe)(nil), "pb.database_subscribe")
	proto.RegisterType((*DatabaseUnsubscribe)(nil), "pb.database_unsubscribe")
	proto.RegisterType((*DatabaseHas)(nil), "pb.database_has")
	proto.RegisterType((*DatabaseHasDb)(nil), "pb.database_has_db")
	proto.RegisterType((*DatabaseWriters)(nil), "pb.database_writers")
	proto.RegisterType((*DatabaseSubscriptionUpdate)(nil), "pb.database_subscription_update")
	proto.RegisterType((*DatabaseRedirectResponse)(nil), "pb.database_redirect_response")
	proto.RegisterType((*DatabaseHasResponse)(nil), "pb.database_has_response")
	proto.RegisterType((*DatabaseHasDbResponse)(nil), "pb.database_has_db_response")
	proto.RegisterType((*DatabaseKeysResponse)(nil), "pb.database_keys_response")
	proto.RegisterType((*DatabaseReadResponse)(nil), "pb.database_read_response")
	proto.RegisterType((*DatabaseQuickReadResponse)(nil), "pb.database_quick_read_response")
	proto.RegisterType((*DatabaseSizeResponse)(nil), "pb.database_size_response")
	proto.RegisterType((*DatabaseRequest)(nil), "pb.database_request")
	proto.RegisterType((*DatabaseWritersResponse)(nil), "pb.database_writers_response")
	proto.RegisterType((*DatabaseTtlResponse)(nil), "pb.database_ttl_response")
	proto.RegisterType((*DatabaseError)(nil), "pb.database_error")
	proto.RegisterType((*DatabaseResponse)(nil), "pb.database_response")
	proto.RegisterType((*DatabaseNullmsg)(nil), "pb.database_nullmsg")
}

func init() { proto.RegisterFile("database.proto", fileDescriptor_b90fe3356ea5df07) }

var fileDescriptor_b90fe3356ea5df07 = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x73, 0xdb, 0x44,
	0x14, 0xf6, 0x4d, 0x8e, 0x75, 0x9c, 0x18, 0x67, 0x93, 0x86, 0x6d, 0x29, 0x90, 0x8a, 0x5b, 0x26,
	0xa4, 0xc1, 0x93, 0x0e, 0x30, 0x4c, 0x0b, 0xd3, 0x06, 0x67, 0xc6, 0x0c, 0xb7, 0x22, 0x9a, 0xe1,
	0x85, 0x19, 0x8d, 0x64, 0x6d, 0x63, 0x4d, 0x6c, 0x49, 0xd5, 0xae, 0x5a, 0xc2, 0x3b, 0x3f, 0x80,
	0x47, 0x7e, 0x0d, 0x6f, 0xfc, 0x2e, 0x66, 0x2f, 0x92, 0x76, 0x6d, 0xc5, 0x9d, 0x4c, 0xdf, 0xd6,
	0x7b, 0xbe, 0xef, 0xec, 0x59, 0x9d, 0xcb, 0x7e, 0x86, 0x41, 0xe8, 0x33, 0x3f, 0xf0, 0x29, 0x39,
	0x4e, 0xb3, 0x84, 0x25, 0xa8, 0x95, 0x06, 0xce, 0x3f, 0x3d, 0xd8, 0x2c, 0xb6, 0xbd, 0x05, 0xbd,
	0x40, 0x9f, 0x42, 0x77, 0x46, 0xfc, 0x90, 0x64, 0xb8, 0xb9, 0xdf, 0x3c, 0xe8, 0x9f, 0xec, 0x1c,
	0xa7, 0xc1, 0x71, 0x89, 0x90, 0x26, 0x57, 0x41, 0xd0, 0x7d, 0xe8, 0x4e, 0x33, 0xe2, 0x33, 0x82,
	0x5b, 0x35, 0x60, 0x69, 0x9a, 0x34, 0x5c, 0x05, 0x42, 0x9f, 0x40, 0x27, 0x23, 0x7e, 0x88, 0xdb,
	0x02, 0xbc, 0x6d, 0x80, 0xb9, 0x61, 0xd2, 0x70, 0x05, 0x80, 0xfb, 0xcd, 0xd3, 0x90, 0xfb, 0xed,
	0xd4, 0xf8, 0x95, 0x26, 0xee, 0x57, 0xae, 0x38, 0x3c, 0x24, 0x73, 0xc2, 0x08, 0xb6, 0x6a, 0xe0,
	0xd2, 0xc4, 0xe1, 0x72, 0x85, 0x3e, 0x84, 0xf6, 0xcc, 0xa7, 0xb8, 0x2b, 0xb0, 0x43, 0xf3, 0x7e,
	0x3e, 0x9d, 0x34, 0x5c, 0x6e, 0x46, 0x87, 0xd0, 0xb9, 0x24, 0x57, 0x14, 0x6f, 0x08, 0xd8, 0xee,
	0x52, 0xb0, 0x2f, 0x72, 0x42, 0x19, 0x8f, 0x97, 0x63, 0x38, 0x96, 0x46, 0x7f, 0x12, 0xdc, 0x5b,
	0x8f, 0xe5, 0x18, 0xf4, 0x05, 0xd8, 0x34, 0x0f, 0xe8, 0x34, 0x8b, 0x02, 0x82, 0x6d, 0x41, 0xd8,
	0x33, 0x08, 0xa5, 0x75, 0xd2, 0x70, 0x2b, 0x28, 0x7a, 0x04, 0xfd, 0x3c, 0xae, 0x98, 0x20, 0x98,
	0xd8, 0xfc, 0x30, 0xb1, 0xce, 0xd5, 0xe1, 0x68, 0x04, 0x1b, 0x71, 0x3e, 0x9f, 0x2f, 0xe8, 0x05,
	0xee, 0xd7, 0x04, 0xa9, 0x6c, 0x93, 0x86, 0x5b, 0xc0, 0xd0, 0x03, 0xb0, 0x65, 0xda, 0xbc, 0x30,
	0xc0, 0x9b, 0x6b, 0x2f, 0xd6, 0x93, 0xc0, 0x71, 0xc0, 0x49, 0xf2, 0x23, 0x73, 0xd2, 0xd6, 0x7a,
	0x92, 0x04, 0x8e, 0x03, 0x74, 0x04, 0xdd, 0x99, 0x4f, 0x39, 0x63, 0x50, 0x57, 0x72, 0xc2, 0x34,
	0x69, 0xb8, 0xd6, 0xcc, 0xa7, 0xe3, 0x80, 0xdf, 0xe4, 0x55, 0x16, 0x31, 0x92, 0x51, 0x3c, 0x5c,
	0x7b, 0x40, 0x01, 0x43, 0x5f, 0x42, 0xdf, 0x0f, 0x43, 0xaf, 0x60, 0x6d, 0xd7, 0xb0, 0x94, 0x6d,
	0xd2, 0x70, 0xc1, 0x0f, 0xc3, 0xdf, 0x14, 0xf1, 0x6b, 0x18, 0x64, 0x64, 0x91, 0xbc, 0x2c, 0xed,
	0x18, 0xad, 0xe5, 0x6e, 0x49, 0x74, 0x41, 0x3f, 0x01, 0x78, 0x91, 0x47, 0xd3, 0x4b, 0x51, 0xdb,
	0x78, 0xe7, 0xfa, 0xa2, 0xb7, 0x05, 0xcc, 0x55, 0x95, 0x4f, 0xfe, 0x48, 0xa3, 0x8c, 0xe0, 0xdd,
	0x9a, 0x6f, 0x21, 0x4d, 0xbc, 0x94, 0xe5, 0x0a, 0xdd, 0x87, 0x8d, 0x94, 0x64, 0x34, 0xa2, 0x0c,
	0xdf, 0xba, 0xde, 0x7f, 0x81, 0x41, 0x1f, 0x41, 0x9b, 0xb1, 0x39, 0xde, 0xbb, 0x1e, 0xca, 0xed,
	0xa7, 0x16, 0xb4, 0x17, 0xf4, 0xc2, 0xf9, 0xbb, 0x09, 0x6f, 0x2d, 0x75, 0x3e, 0x7a, 0x1b, 0x36,
	0xc2, 0xc0, 0xcb, 0xf3, 0x28, 0x14, 0xf3, 0xc1, 0x76, 0xbb, 0x61, 0x70, 0x9e, 0x47, 0x21, 0xc2,
	0x60, 0xc5, 0x49, 0x3c, 0x95, 0x93, 0xa0, 0x73, 0xda, 0x1a, 0x35, 0x5d, 0xb9, 0x81, 0x0e, 0x60,
	0x98, 0x26, 0x51, 0xcc, 0xbc, 0xe4, 0xb9, 0x37, 0x4d, 0x62, 0xe6, 0x4f, 0x99, 0x98, 0x00, 0xb6,
	0x3b, 0x10, 0xfb, 0x3f, 0x3f, 0xff, 0x56, 0xee, 0xa2, 0x7b, 0xb0, 0xa9, 0xd2, 0xc7, 0xb3, 0x3e,
	0x13, 0xcd, 0xbf, 0xe9, 0xf6, 0x8b, 0x94, 0xfa, 0x74, 0xe6, 0xfc, 0xa2, 0x85, 0xa4, 0xa6, 0xca,
	0x10, 0xda, 0x97, 0xe4, 0x4a, 0x85, 0xc3, 0x97, 0x68, 0x17, 0xac, 0x97, 0xfe, 0x3c, 0x97, 0xb1,
	0x6c, 0xba, 0xf2, 0x07, 0xda, 0x2b, 0x3f, 0x2d, 0x3f, 0xbd, 0x53, 0x7c, 0x43, 0xe7, 0x1e, 0x6c,
	0x19, 0x5f, 0x61, 0xd5, 0xa1, 0x71, 0xaa, 0x9a, 0x39, 0x6f, 0x7a, 0xea, 0x43, 0xcd, 0xa5, 0x4a,
	0xe6, 0xaa, 0xcb, 0x8a, 0xdc, 0x32, 0xc8, 0x1f, 0x68, 0x64, 0x35, 0xd4, 0x56, 0x83, 0xfe, 0x18,
	0xd0, 0xea, 0x4c, 0xa9, 0xc1, 0x7d, 0x03, 0xbb, 0x75, 0x13, 0xa4, 0xfe, 0x86, 0x5a, 0x8e, 0x55,
	0x7e, 0x9d, 0x7d, 0xed, 0x05, 0xe1, 0x83, 0x73, 0xf5, 0x84, 0x6d, 0xbd, 0x8e, 0x44, 0x3b, 0x3b,
	0x47, 0x30, 0x5c, 0x6e, 0x20, 0x84, 0xab, 0xce, 0x6e, 0xee, 0xb7, 0x0f, 0xec, 0xb2, 0x83, 0x9d,
	0x7f, 0x9b, 0x70, 0x77, 0xf9, 0x2e, 0x29, 0x8b, 0x92, 0xf8, 0xa6, 0xd9, 0xf8, 0x11, 0xec, 0x24,
	0x25, 0x99, 0xcf, 0xb9, 0x22, 0x21, 0x83, 0x93, 0xcf, 0xea, 0x86, 0xaf, 0xee, 0xfc, 0xb8, 0x64,
	0x78, 0xec, 0x2a, 0x25, 0x6e, 0xe5, 0xc1, 0x39, 0x80, 0x81, 0x69, 0x44, 0x00, 0xdd, 0xf3, 0xa7,
	0xe3, 0x27, 0xcf, 0xce, 0x86, 0x0d, 0xbe, 0x1e, 0x9f, 0xfd, 0x70, 0xf6, 0xec, 0x6c, 0xd8, 0x74,
	0xfe, 0x6b, 0xc2, 0x1d, 0xad, 0xca, 0xc2, 0x28, 0x23, 0x53, 0xe6, 0x65, 0x84, 0xa6, 0x49, 0x4c,
	0x09, 0x7a, 0x07, 0xec, 0xb9, 0x68, 0x30, 0xaf, 0x6c, 0xac, 0x9e, 0xdc, 0xf8, 0x2e, 0x44, 0xef,
	0x43, 0x5f, 0x19, 0x63, 0x7f, 0x21, 0x2f, 0x64, 0xbb, 0x20, 0xb7, 0x7e, 0xf2, 0x17, 0x44, 0x03,
	0xcc, 0x12, 0x5a, 0x34, 0x97, 0x02, 0x4c, 0x12, 0xca, 0x34, 0x40, 0x9a, 0x64, 0x4c, 0xf4, 0xd5,
	0x56, 0x01, 0x78, 0x9a, 0x64, 0x8c, 0xf7, 0x68, 0xe1, 0x81, 0xb1, 0x54, 0xa2, 0x2c, 0x81, 0x1a,
	0x28, 0x37, 0x8c, 0xa5, 0x1c, 0xe9, 0x3c, 0x84, 0x5b, 0x46, 0x2e, 0xcb, 0x2b, 0xac, 0xa6, 0x60,
	0x28, 0xdf, 0x59, 0x1e, 0x6f, 0x4f, 0xbc, 0xa9, 0xce, 0x63, 0xc0, 0x4b, 0x85, 0x50, 0xf1, 0x11,
	0x74, 0xb4, 0xb1, 0x22, 0xd6, 0x35, 0x1e, 0x8e, 0x60, 0xaf, 0xf4, 0xc0, 0x9f, 0x5e, 0x83, 0x2f,
	0xde, 0x6b, 0x59, 0x3a, 0x62, 0xed, 0x3c, 0xd6, 0xd0, 0xbc, 0xb5, 0xd7, 0x45, 0x5b, 0x5b, 0x30,
	0xce, 0xef, 0x5a, 0xe1, 0x55, 0xc3, 0xfc, 0xc6, 0x7e, 0xf8, 0x2e, 0xc9, 0xb2, 0x24, 0x53, 0xc9,
	0x91, 0x3f, 0x9c, 0x53, 0x2d, 0x3e, 0x2e, 0x0e, 0x2a, 0xbf, 0xbb, 0x60, 0x05, 0x57, 0x8c, 0x50,
	0xe1, 0xd9, 0x72, 0xe5, 0x8f, 0xf2, 0x8e, 0x2d, 0xb1, 0x29, 0xef, 0x88, 0xb4, 0x4e, 0x52, 0x93,
	0xd2, 0xf9, 0x1e, 0x6e, 0x2f, 0x77, 0x97, 0xe1, 0x3a, 0x79, 0x15, 0x2b, 0x81, 0x67, 0xbb, 0xf2,
	0x87, 0xde, 0x7c, 0x2d, 0xb3, 0xf9, 0xf4, 0x8c, 0x33, 0x36, 0x7f, 0x4d, 0xc6, 0xf9, 0xfb, 0x22,
	0xc7, 0x03, 0x5f, 0x3a, 0x87, 0x95, 0xea, 0xf4, 0xc4, 0x9d, 0xf9, 0x41, 0x0b, 0x42, 0xa9, 0x7f,
	0x41, 0x14, 0xb3, 0xf8, 0xe9, 0xfc, 0x65, 0xc1, 0xb6, 0x76, 0x15, 0x75, 0xca, 0x8d, 0x04, 0xe9,
	0x23, 0xe8, 0x15, 0xcd, 0xa5, 0x24, 0xe9, 0x7b, 0x4b, 0xaf, 0xdc, 0x52, 0xe7, 0x71, 0x21, 0x52,
	0x6c, 0xa2, 0x5f, 0x61, 0xa7, 0xa6, 0xff, 0x95, 0x5c, 0xdd, 0x7f, 0xdd, 0x9c, 0x98, 0x34, 0x5c,
	0xa4, 0x6f, 0x9f, 0xcb, 0xd1, 0x34, 0x52, 0xa2, 0x57, 0x2a, 0xd9, 0x3b, 0x2b, 0x8f, 0xae, 0x1e,
	0x8a, 0x54, 0xbf, 0x4f, 0x0c, 0xdd, 0x60, 0xd5, 0x9c, 0x5e, 0x53, 0x89, 0xcb, 0x32, 0x42, 0x93,
	0xb8, 0xb7, 0x57, 0xf4, 0x94, 0x46, 0x12, 0x5a, 0x77, 0x64, 0x68, 0x5d, 0x33, 0x46, 0xa3, 0xcb,
	0x4a, 0xc5, 0x3b, 0x32, 0x14, 0xaf, 0xc9, 0x30, 0x2a, 0xb9, 0xd4, 0xbd, 0x87, 0x45, 0x07, 0x48,
	0xcd, 0x8b, 0x4c, 0x61, 0xc3, 0x2d, 0x5c, 0xe3, 0xc9, 0x1a, 0xf9, 0xbc, 0x54, 0x84, 0x52, 0xe6,
	0xde, 0xad, 0x51, 0x84, 0xfa, 0x09, 0x4a, 0x1a, 0x7e, 0x55, 0xd5, 0xb0, 0x14, 0xb9, 0xef, 0xd6,
	0x09, 0x35, 0x9d, 0x58, 0xe0, 0x4f, 0x81, 0x17, 0x8e, 0xdc, 0x36, 0x3a, 0x4a, 0xa9, 0xe1, 0xa0,
	0x2b, 0xfe, 0x32, 0x3d, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x3a, 0x57, 0x9e, 0x44, 0x0d,
	0x00, 0x00,
}
