// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	SwarmVersion         string   `protobuf:"bytes,1,opt,name=swarm_version,json=swarmVersion,proto3" json:"swarm_version,omitempty"`
	SwarmGitCommit       string   `protobuf:"bytes,2,opt,name=swarm_git_commit,json=swarmGitCommit,proto3" json:"swarm_git_commit,omitempty"`
	Uptime               string   `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	ModuleStatusJson     string   `protobuf:"bytes,4,opt,name=module_status_json,json=moduleStatusJson,proto3" json:"module_status_json,omitempty"`
	PbftEnabled          bool     `protobuf:"varint,5,opt,name=pbft_enabled,json=pbftEnabled,proto3" json:"pbft_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetSwarmVersion() string {
	if m != nil {
		return m.SwarmVersion
	}
	return ""
}

func (m *StatusResponse) GetSwarmGitCommit() string {
	if m != nil {
		return m.SwarmGitCommit
	}
	return ""
}

func (m *StatusResponse) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *StatusResponse) GetModuleStatusJson() string {
	if m != nil {
		return m.ModuleStatusJson
	}
	return ""
}

func (m *StatusResponse) GetPbftEnabled() bool {
	if m != nil {
		return m.PbftEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "pb.status_request")
	proto.RegisterType((*StatusResponse)(nil), "pb.status_response")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_dfe4fce6682daf5b) }

var fileDescriptor_dfe4fce6682daf5b = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x71, 0xf6, 0xd4, 0x43, 0xc7, 0xf5, 0x5c, 0x52, 0x48, 0xca, 0xf3, 0x6c, 0xb6, 0x10,
	0x1b, 0x1f, 0x41, 0x44, 0xb0, 0x3c, 0xc1, 0x36, 0x6c, 0xbc, 0x51, 0x22, 0x97, 0x4c, 0xcc, 0x4c,
	0xf4, 0x19, 0x7d, 0x2b, 0x71, 0xb2, 0x5c, 0x99, 0xdf, 0xf7, 0x2f, 0x32, 0xd0, 0xb3, 0x4c, 0x52,
	0xf9, 0x2e, 0x17, 0x12, 0x32, 0x8b, 0xec, 0x37, 0x03, 0xac, 0x9a, 0xb9, 0x82, 0x5f, 0x15, 0x59,
	0x36, 0xbf, 0x1d, 0x5c, 0x1e, 0x88, 0x33, 0x25, 0x46, 0x73, 0x03, 0x17, 0xfc, 0x33, 0x95, 0xe8,
	0xbe, 0xb1, 0x70, 0xa0, 0x64, 0xbb, 0x75, 0x37, 0x9e, 0x6d, 0x7b, 0xc5, 0xd7, 0x66, 0x66, 0x84,
	0xa1, 0x45, 0x1f, 0x41, 0xdc, 0x1b, 0xc5, 0x18, 0xc4, 0x2e, 0xb4, 0x5b, 0xa9, 0x3f, 0x05, 0x79,
	0x50, 0x35, 0x57, 0xb0, 0xac, 0x59, 0x42, 0x44, 0x7b, 0xa4, 0xfb, 0xfc, 0x32, 0xb7, 0x60, 0x22,
	0xed, 0xea, 0x1e, 0xdd, 0xfc, 0x81, 0x4f, 0xa6, 0x64, 0x8f, 0xb5, 0x19, 0xda, 0xf2, 0xa2, 0xc3,
	0x33, 0x53, 0x32, 0xd7, 0xd0, 0x67, 0xff, 0x2e, 0x0e, 0xd3, 0xe4, 0xf7, 0xb8, 0xb3, 0x27, 0xeb,
	0x6e, 0x3c, 0xdd, 0x9e, 0xff, 0xdb, 0x63, 0x23, 0xbf, 0xd4, 0x43, 0xef, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x17, 0x40, 0x7b, 0xdd, 0xf8, 0x00, 0x00, 0x00,
}
